# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: seerr
spec:
  interval: 60m
  chart:
    spec:
      chart: seerr-chart
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: seerr
  rollback:
    cleanupOnFail: true
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
        kubernetes.io/tls-acme: "true"

      hosts:
        - host: seerr.${BCL_GLOBAL_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific

      tls:
        - secretName: tls-seer
          hosts:
            - seerr.${BCL_GLOBAL_DOMAIN}

    config:
      persistence:
        volumeName: seerr
