apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: infra
spec:
  interval: 10m0s
  path: ./kube/lar
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
