resources:
  configMaps:
    main:
      data:
        main: cm
    toto:
      labels:
        app: genre
        truc: bidule
      data:
        something: interesting
      binaryData:
        blob: aGVsbG8=
  secrets:
    titi:
      labels:
        app: genre2
        truc: bidule2
      stringData:
        something: interesting
  horizontalPodAutoscalers:
    myhpa:
      nameOverride: override
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: myapp
      minReplicas: 1
      maxReplicas: 3
  services:
    myservice:
      fullnameOverride: fulloverride
      selector:
        app: myapp
      ports:
        - port: 80
          targetPort: 8080
