---
# Source: resources-test/templates/loader.yaml
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: test-release
  namespace: default
spec:
  fields:
  - fieldName: token
