---
# Source: resources-test/templates/loader.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: test-release
  namespace: default
spec:
  host: myapp.example.com
  port:
    targetPort: http
  to:
    kind: Service
    name: myapp
