---
# Source: resources-test/templates/loader.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: test-release
  namespace: default
spec:
  encryptedData:
    password: AgBy8hIFn8...encrypted...
