---
# Source: resources-test/templates/loader.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: test-release
  namespace: default
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets
      remoteNamespace: authelia
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
