# yaml-language-server: $schema=../values.schema.json

defaults:
  resources:
    configMaps:
      labels:
        app: shared-default
        team: platform

resources:
  configMaps:
    usesDefaultOnly:
      data:
        key: value1
    overridesDefault:
      labels:
        app: custom-app
      data:
        key: value2
