---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-overridesDefault
  namespace: default
  labels:
    app: custom-app
    team: platform
data:
  key: value2
---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-usesDefaultOnly
  namespace: default
  labels:
    app: shared-default
    team: platform
data:
  key: value1
