# yaml-language-server: $schema=../values.schema.json

resources:
  configMaps:
    main:
      data:
        a: b
  services:
    main:
      selector:
        app: x
      ports:
        - port: 80
