---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-release
stringData:
  a: b
---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-release-my-custom-id
stringData:
  a: b
---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-release-plain
stringData:
  a: b
