# yaml-language-server: $schema=../values.schema.json

resources:
  clusterRoleBindings:
    main:
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: myapp-cluster-role
      subjects:
        - kind: ServiceAccount
          name: myapp
          namespace: default
