# yaml-language-server: $schema=../values.schema.json

resources:
  cronJobs:
    main:
      schedule: "*/5 * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              restartPolicy: Never
              containers:
                - name: myapp
                  image: myimage:latest
