# yaml-language-server: $schema=../values.schema.json

resources:
  configMaps:
    defaultEnabled:
      data:
        main: cm
    explicitlyEnabled:
      enabled: true
      data:
        main: cm
    disabled:
      enabled: false
      data:
        main: cm
