# yaml-language-server: $schema=../values.schema.json

resources:
  gitRepositories:
    main:
      interval: 5m
      url: https://github.com/fluxcd/flux2-kustomize-helm-example
      ref:
        branch: main
