# yaml-language-server: $schema=../values.schema.json

resources:
  ingresses:
    main:
      rules:
        - host: myapp.example.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: myapp
                    port:
                      number: 80
