# yaml-language-server: $schema=../values.schema.json

resources:
  networkAttachmentDefinitions:
    br0-dhcp:
      config: |
        {
          "cniVersion": "0.3.0",
          "name": "mymacvlan",
          "plugins": [
            {
              "type": "macvlan",
              "master": "br0",
              "mode": "bridge",
              "ipam": {
                "type": "dhcp",
                "request": [
                  {
                    "skipDefault": true,
                    "option": "subnet-mask"
                  }
                ]
              }
            }
          ]
        }
