# yaml-language-server: $schema=../values.schema.json

resources:
  persistentVolumes:
    main:
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: /mnt/data
