# yaml-language-server: $schema=../values.schema.json

resources:
  roleBindings:
    main:
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: myapp-role
      subjects:
        - kind: ServiceAccount
          name: myapp
          namespace: default
