# yaml-language-server: $schema=../values.schema.json

resources:
  statefulSets:
    main:
      serviceName: myapp
      selector:
        matchLabels:
          app: myapp
      template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
            - name: myapp
              image: myimage:latest
