# yaml-language-server: $schema=../values.schema.json

resources:
  udpRoutes:
    main:
      parentRefs:
        - name: main-gateway
      rules:
        - backendRefs:
            - name: main-service
              port: 53
