---
# Source: resources-test/templates/loader.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: test-release
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main
  updatePolicy:
    updateMode: Auto
