# yaml-language-server: $schema=../values.schema.json

resources:
  volumeSnapshotClasses:
    main:
      driver: driver.longhorn.io
      deletionPolicy: Delete
      parameters:
        type: snap
