creation_rules:
  - path_regex: flux/lmr.*
    encrypted_regex: '^(data|stringData)$'
    key_groups:
    - age:
      - *n0rad
      - *srv

  - path_regex: flux/pop.*
    encrypted_regex: '^(data|stringData)$'
    key_groups:
    - age:
      - *n0rad
      - *pop

  - path_regex: terraform/.*/.*.enc.yaml
    key_groups:
    - age:
      - *n0rad

  - path_regex: nixos/.*/secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *media
      - *n0
      - *srv
      - *media
      - *hideki
      - *install
      - *dl
  - path_regex: nixos/.*/roles/dl.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *dl
  - path_regex: nixos/.*/roles/install.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *install
  - path_regex: nixos/.*/roles/media.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *media
  - path_regex: nixos/.*/roles/srv.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *srv
  - path_regex: nixos/.*/roles/srv-backup.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *srv-backup
  - path_regex: nixos/.*/roles/n0.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *n0
  - path_regex: nixos/.*/roles/hideki.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *hideki
  - path_regex: nixos/.*/roles/game.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *game
  - path_regex: nixos/.*/roles/pop.secrets.yaml
    key_groups:
    - age:
      - *n0rad
      - *pop
