# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns
  namespace: bcl
spec:
  interval: 10m
  path: ./kube/apps/coredns
  prune: false  # too dangerous to prune, would lose dns
  sourceRef:
    kind: GitRepository
    name: bcl
  wait: true
  postBuild:
    substituteFrom:
      - name: global-env
        kind: ConfigMap
