# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: bcl
spec:
  interval: 1h
  path: ./kube/apps/flux
  prune: false # too dangerous to prune flux itself
  sourceRef:
    kind: GitRepository
    name: bcl
  wait: true
