{ config, lib, ... }:
let
  cfg = config.bcl.container;
  macvlanNetworkName = bridge: "${bridge}-macvlan";
in
{
  options.bcl.container.containers = lib.mkOption {
    type = lib.types.attrsOf (lib.types.submodule ({ name, ... }: {
      options = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Whether this container should be started.";
        };
        image = lib.mkOption {
          type = lib.types.str;
          description = "Container image to run, e.g. \"ghcr.io/becloudless/alpine-kubelet:1.2.3\".";
        };
        volumes = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          description = ''
            Volumes to mount into the container, in Docker's
            `hostPath:containerPath[:opts]` format.
          '';
          example = [ "/var/lib/foo:/data" "/etc/foo.conf:/etc/foo.conf:ro" ];
        };
        files = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = { };
          apply = lib.mapAttrs' (path: content: lib.nameValuePair (lib.removePrefix "/" path) content);
          description = ''
            Files to make available inside the container, as an attrset of
            the container's absolute path (with or without the leading
            "/", e.g. "etc/kubernetes/foo.yaml") to its content. Each file
            is created on the host as a nix-managed symlink under
            `/etc/containers-files/<name>/<path>` and bind-mounted
            read-only into the container at `/<path>`.
          '';
          example = {
            "etc/foo.conf" = "hello=world";
          };
        };
        extraOptions = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          description = ''
            Extra command-line arguments to pass to `docker run` for this
            container (e.g. "--privileged", "--pid=host"), in addition to
            any generated by `network`.
          '';
          example = [ "--privileged" "--pid=host" ];
        };
        cmd = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          description = ''
            Command (and arguments) to run in the container, overriding its
            image's default entrypoint/cmd.
          '';
          example = [ "sh" "-c" "echo hello" ];
        };
        network = lib.mkOption {
          type = lib.types.nullOr (lib.types.submodule (net: {
            options = {
              bridge = lib.mkOption {
                type = lib.types.str;
                description = ''
                  Network bridge (e.g. "br0", "br50") to give this
                  container its own isolated network identity on, via a
                  macvlan network attached to that bridge - instead of
                  sharing the host's network namespace.
                '';
              };
              cidr = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = ''
                  CIDR subnet of the bridge's network, e.g.
                  "192.168.50.0/24". Only needed if `address` is set, or if
                  Docker's own auto-assigned subnet (unrelated to the real
                  network the bridge is attached to) would be a problem.
                '';
              };
              gateway = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = lib.mapNullable (s: lib.bcl.net.cidrhost s (-2)) net.config.cidr;
                defaultText = lib.literalExpression "last usable address of `cidr`";
                description = "Gateway for `cidr`.";
              };
              address = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = ''
                  Static IP address (within `cidr`, no prefix length) to
                  assign to this container from the host, instead of
                  relying on DHCP/autoconfiguration inside the container.
                '';
                example = "192.168.50.10";
              };
              nameservers = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = lib.optional (net.config.gateway != null) net.config.gateway;
                defaultText = lib.literalExpression "[ gateway ]";
                description = ''
                  DNS nameservers for the container. A dedicated network
                  namespace has no access to the host's own resolv.conf,
                  so this defaults to `gateway` (mirroring `bcl.network`).
                '';
              };
            };
          }));
          default = null;
          description = ''
            Network to attach this container to, via a dedicated macvlan
            network. If null, the container uses Docker's default networking.
          '';
        };
      };
    }));
    default = { };
    description = ''
      Declarative Docker containers to run on this host.
    '';
  };

  config = lib.mkIf (cfg.containers != { }) {
    virtualisation.oci-containers.backend = "docker";

    environment.etc = lib.mkMerge (lib.mapAttrsToList
      (name: c: lib.mapAttrs'
        (path: content: lib.nameValuePair "containers-files/${name}/${path}" { text = content; })
        c.files)
      cfg.containers);

    virtualisation.oci-containers.containers = lib.mapAttrs
      (name: c: ({
        image = c.image;
        autoStart = c.enable;
        cmd = c.cmd;
        volumes = c.volumes ++ (map
          (path: "/etc/containers-files/${name}/${path}:/${path}:ro")
          (builtins.attrNames c.files));
        extraOptions = [ "--hostname=${name}" ] ++ c.extraOptions
          ++ lib.optionals (c.network != null) (
            lib.optional (c.network.address != null) "--ip=${c.network.address}"
            ++ map (ns: "--dns=${ns}") c.network.nameservers
          );
      } // lib.optionalAttrs (c.network != null) {
        networks = [ (macvlanNetworkName c.network.bridge) ];
      }))
      cfg.containers;

    # For each distinct bridge referenced by a container, create a macvlan
    # Docker network attached to it, giving containers their own L2/L3
    # identity on it instead of sharing the host's network namespace
    # wholesale. If several containers share the same bridge, the first
    # one's cidr/gateway (if any) is used.
    systemd.services = lib.mkMerge [
      (lib.mapAttrs'
        (bridge: net:
          let
            network = macvlanNetworkName bridge;
          in
          lib.nameValuePair "docker-network-${network}" {
            after = [ "docker.service" "sys-subsystem-net-devices-${bridge}.device" ];
            requires = [ "docker.service" ];
            bindsTo = [ "sys-subsystem-net-devices-${bridge}.device" ];
            path = [ config.virtualisation.docker.package ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
            };
            script = ''
              existing_subnet=$(docker network inspect ${network} --format '{{ (index .IPAM.Config 0).Subnet }}' 2>/dev/null || true)
              existing_gateway=$(docker network inspect ${network} --format '{{ (index .IPAM.Config 0).Gateway }}' 2>/dev/null || true)
              desired_subnet=${lib.optionalString (net.cidr != null) net.cidr}
              desired_gateway=${lib.optionalString (net.gateway != null) net.gateway}

              # Docker networks are immutable once created: if this network
              # already exists but with a different (or no) subnet/gateway
              # than currently desired - e.g. it was first created before
              # `cidr`/`gateway` were set, or were since changed - `docker
              # network create`'s own idempotency check (inspect-then-create)
              # would otherwise silently keep the STALE subnet/gateway
              # forever. A stale subnet causes `docker run --ip=...` to
              # fail outright ("no configured subnet contains IP address
              # ..."); a stale gateway fails silently (containers just keep
              # routing through the old gateway). Recreate the network
              # whenever either no longer matches what's desired.
              if [ -n "$existing_subnet" ] && { [ "$existing_subnet" != "$desired_subnet" ] || [ "$existing_gateway" != "$desired_gateway" ]; }; then
                docker network rm ${network}
                existing_subnet=""
              fi

              [ -n "$existing_subnet" ] || \
                docker network create -d macvlan -o parent=${bridge} \
                  ${lib.optionalString (net.cidr != null) "--subnet=${net.cidr}"} \
                  ${lib.optionalString (net.gateway != null) "--gateway=${net.gateway}"} \
                  ${network}
            '';
          })
        (lib.listToAttrs (map (c: lib.nameValuePair c.network.bridge c.network)
          (lib.filter (c: c.network != null) (lib.attrValues cfg.containers)))))

      # Every container attached to a macvlan network must wait for its
      # network to actually exist first - otherwise `docker run` fails with
      # "network <name> not found" (the oci-containers-generated
      # docker-<name>.service has no notion of this dependency on its own).
      (lib.mapAttrs'
        (name: c: lib.nameValuePair "docker-${name}" {
          after = [ "docker-network-${macvlanNetworkName c.network.bridge}.service" ];
          requires = [ "docker-network-${macvlanNetworkName c.network.bridge}.service" ];
        })
        (lib.filterAttrs (name: c: c.network != null) cfg.containers))
    ];
  };
}
