apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-postgresql-replication
  namespace: immich
spec:
  secretName: immich-postgresql-replication-tls
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: immich-postgresql
    kind: Issuer

