apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-postgresql-app
  namespace: forgejo
spec:
  secretName: forgejo-postgresql-app-tls
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  commonName: app
  issuerRef:
    name: forgejo-postgresql
    kind: Issuer

