# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 60m
  chart:
    spec:
      chart: base-template
      version: 1.250501.709-Heffe9b6
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: flux-system
  rollback:
    cleanupOnFail: true
  values:
    mainWorkload:
      type: singleton

      pod:
        securityContext:
          runAsNonRoot: false

      container:
        image:
          repository: ghcr.io/jellyfin/jellyfin
          tag: 10.11.4
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
        probes:
          startup:
            spec:              
              failureThreshold: 60 # 10min, huge Jellyfin can be slow to start

      service:
        ports:
          http:
            port: 8096

      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: jellyfin.${BCL_GLOBAL_DOMAIN}
            paths:
              - path: /
                service:
                  name: jellyfin
                  port: 8096
        tls:
          - secretName: tls-jellyfin
            hosts:
              - jellyfin.${BCL_GLOBAL_DOMAIN}

      volumes:
#        secrets:
#          type: secret
#          name: jellyfin
#          path: /config/plugins/configurations/SSO-Auth.xml
#          subPath: SSO-Auth.xml
        config:
          type: persistentVolumeClaim
        video:
          type: hostPath
          path: /data/Videos
          hostPath: /data/Videos
          # mountPropagation: Bidirectional
        audio:
          type: hostPath
          path: /data/Audio
          hostPath: /data/Audio
          # mountPropagation: Bidirectional
        image:
          type: hostPath
          path: /data/Images
          hostPath: /data/Images
          # mountPropagation: Bidirectional

#        download:
#          type: hostPath
#          path: /data/Downloads
#          hostPath: /data/Downloads


    resources:
#      controllers:
#        main:
#          containers:
#            images:
#              image:
#                repository: gitea.lmr.io/lmr/alpine-backup-tools
#                tag: 1.250323.1327-h9c5ad5b8
#              command: ["sh"]
#              args:
#              - -c
#              - |
#                while true; do
#                  mkdir -p /data/download/image/tv
#                  find /config/metadata/library/ -name backdrop1.jpg -exec bash -c 'id=$(echo {} | sed "s/.*\([a-z0-9]\{32\}\).*/\1/") && cp {} "/data/download/image/tv/$id.jpg"' \;
#
#                  mkdir -p /data/download/image/movie
#                  find /config/metadata/library/ -name backdrop.jpg -exec bash -c 'id=$(echo {} | sed "s/.*\([a-z0-9]\{32\}\).*/\1/") && cp {} "/data/download/image/movie/$id.jpg"' \;
#
#                  sleep 7d
#                done

      persistentVolumeClaims:
        config:
          storageClass: jellyfin-config
      persistentVolumes:
        config:
          storageClassName: jellyfin-config
          csi:
            driver: driver.longhorn.io
            volumeHandle: jellyfin-config
