# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 60m
  chart:
    spec:
      chart: base-template
      version: 1.250501.709-Heffe9b6
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: bcl
  rollback:
    cleanupOnFail: true
  values:
    mainWorkload:
      type: singleton

      pod:
        securityContext:
          runAsNonRoot: false

      container:
        image:
          repository: ghcr.io/jellyfin/jellyfin
          tag: 10.11.6
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
        probes:
          startup:
            spec:
              failureThreshold: 60 # 10min, huge Jellyfin on low hardware can be slow to start

      service:
        ports:
          http:
            port: 8096

      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: jellyfin.${BCL_GLOBAL_DOMAIN}
            paths:
              - path: /
                service:
                  name: jellyfin
                  port: 8096
        tls:
          - secretName: tls-jellyfin
            hosts:
              - jellyfin.${BCL_GLOBAL_DOMAIN}

      volumes:
        branding:
          type: configMap
          name_resource: main
          path: /config/config/branding.xml
          subPath: branding.xml
        network:
          type: configMap
          name_resource: main
          path: /config/config/network.xml
          subPath: network.xml

#        secrets:
#          type: secret
#          name: jellyfin
#          path: /config/plugins/configurations/SSO-Auth.xml
#          subPath: SSO-Auth.xml
        config:
          type: persistentVolumeClaim
        video:
          type: hostPath
          path: /data/Videos
          hostPath: /data/Videos
          # mountPropagation: Bidirectional
        audio:
          type: hostPath
          path: /data/Audio
          hostPath: /data/Audio
          # mountPropagation: Bidirectional
        image:
          type: hostPath
          path: /data/Images
          hostPath: /data/Images
          # mountPropagation: Bidirectional
        downloads:
          type: hostPath
          path: /data/Downloads
          hostPath: /data/Downloads


    resources:
      configMaps:
        main:
          data:
            branding.xml: |
              <BrandingOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                <LoginDisclaimer>&lt;form action="https://jellyfin.${BCL_GLOBAL_DOMAIN}/sso/OID/start/authelia"&gt;
                    &lt;button class="raised block emby-button button-submit"&gt;
                    Sign in with Authelia
                    &lt;/button&gt;
                  &lt;/form&gt;</LoginDisclaimer>
                <CustomCss>
                  /* Hide manual login form */
                  .manualLoginForm {
                    display: none !important;
                  }
                  .updatePasswordForm  {
                    display: none !important;
                  }

                  /* Hide 'Forgot password' button */
                  .btnForgotPassword {
                    display: none !important;
                  }

                  /* Add SSO button */
                  a.raised.emby-button {
                    padding:0.9em 1em;
                    color: inherit !important;
                  }

                  .disclaimerContainer{
                    display: block;
                  }
                </CustomCss>
                <SplashscreenEnabled>false</SplashscreenEnabled>
              </BrandingOptions>

            network.xml: |
              <?xml version="1.0" encoding="utf-8"?>
              <NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                <BaseUrl />
                <EnableHttps>false</EnableHttps>
                <RequireHttps>false</RequireHttps>
                <InternalHttpPort>8096</InternalHttpPort>
                <InternalHttpsPort>8920</InternalHttpsPort>
                <PublicHttpPort>8096</PublicHttpPort>
                <PublicHttpsPort>8920</PublicHttpsPort>
                <AutoDiscovery>true</AutoDiscovery>
                <EnableIPv4>true</EnableIPv4>
                <EnableIPv6>false</EnableIPv6>
                <EnableRemoteAccess>true</EnableRemoteAccess>
                <LocalNetworkSubnets />
                <LocalNetworkAddresses />
                <KnownProxies>
                  <string>10.42.0.0/16</string>
                </KnownProxies>
                <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
                <VirtualInterfaceNames>
                  <string>veth</string>
                </VirtualInterfaceNames>
                <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
                <PublishedServerUriBySubnet />
                <RemoteIPFilter />
                <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
              </NetworkConfiguration>


      controllers:
        main:
          containers:
            images:
              image:
                repository: ghcr.io/becloudless/alpine
                tag: 1.260202.1736-H7074dbd
              command: ["sh"]
              args:
              - -c
              - |
                while true; do
                  mkdir -p /data/Downloads/Images/Backdrops
                  find /config/metadata/library/ -name backdrop.jpg -exec bash -c 'id=$(echo {} | sed "s/.*\([a-z0-9]\{32\}\).*/\1/") && cp {} "/data/Downloads/Images/Backdrops/$id.jpg"' \;
                  sleep 7d
                done

      persistentVolumeClaims:
        config:
          storageClass: jellyfin-config
      persistentVolumes:
        config:
          storageClassName: jellyfin-config
          csi:
            driver: driver.longhorn.io
            volumeHandle: jellyfin-config
