bcl:
    global:
        enable: true
        networking:
            domain: demo.example.local
    system:
        enable: true
        hardware: nuc
        role: tv
        ids: uuid=XXXXX
        devices:
            - /dev/disk/by-id/XXXXX

    boot:
        efi: false
