package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// generateTemplate writes templates/_generated.tpl: a "resources.render"
// aggregate that, for every resource kind in resources.yaml, includes the generic
// "resources.generic.renderAll" template defined in
// templates/_renderAll.tpl.
func generateTemplate(dir string, entries []resource) error {
	templatesDir := filepath.Join(dir, "templates")
	if err := os.MkdirAll(templatesDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", templatesDir, err)
	}

	var sb strings.Builder
	sb.WriteString("{{/*\nAUTO-GENERATED by the build tool (see generate/) from resources.yaml. Do not edit manually.\n*/}}\n\n")

	sb.WriteString(`{{- define "resources.render" }}
  {{- $rootContext := .rootContext }}
`)
	for _, e := range entries {
		if e.apiVersion == "" || e.kind == "" {
			return fmt.Errorf("resource %q is missing apiVersion/kind in resources.yaml", e.name)
		}

		args := []string{fmt.Sprintf(`"rootContext" $rootContext "name" %q "apiVersion" %q "kind" %q`, e.name, e.apiVersion, e.kind)}
		for _, arg := range e.templateArgs {
			args = append(args, fmt.Sprintf(`%q %s`, arg.Name, arg.Value))
		}
		fmt.Fprintf(&sb, `  {{- include "resources.generic.renderAll" (dict %s) }}
`, strings.Join(args, " "))
	}
	sb.WriteString("{{- end }}\n")

	dest := filepath.Join(templatesDir, "_generated.tpl")
	fmt.Printf("generating %s\n", dest)
	return os.WriteFile(dest, []byte(sb.String()), 0o644)
}
