package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// entry represents one resource kind declared in CRDs.yaml, e.g.:
//
//	configMaps:
//	  url: https://...configmap.json
//	  apiVersion: v1
//	  kind: ConfigMap
//	  contentIsSpec: false
type entry struct {
	name          string
	url           string
	apiVersion    string
	kind          string
	contentIsSpec bool // defaults to true; set contentIsSpec: false in CRDs.yaml to override
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run() error {
	dir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}

	yamlPath := filepath.Join(dir, "CRDs.yaml")
	entries, err := parseCRDs(yamlPath)
	if err != nil {
		return fmt.Errorf("parse %s: %w", yamlPath, err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("no entries found in %s", yamlPath)
	}

	if err := fetchSchemas(dir, entries); err != nil {
		return err
	}

	if err := generateTemplate(dir, entries); err != nil {
		return err
	}

	return nil
}

func fetchSchemas(dir string, entries []entry) error {
	schemaDir := filepath.Join(dir, "schema", "resources")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", schemaDir, err)
	}

	client := &http.Client{Timeout: 30 * time.Second}

	var failed []string
	for _, e := range entries {
		if e.url == "" {
			continue
		}
		dest := filepath.Join(schemaDir, e.name+".json")
		fmt.Printf("fetching %s -> %s\n", e.url, dest)
		if err := fetchToFile(client, e.url, dest); err != nil {
			fmt.Fprintf(os.Stderr, "  failed: %v\n", err)
			failed = append(failed, e.name)
			continue
		}
	}

	if len(failed) > 0 {
		return fmt.Errorf("failed to fetch schemas: %s", strings.Join(failed, ", "))
	}
	return nil
}

func fetchToFile(client *http.Client, url, dest string) error {
	resp, err := client.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("unexpected status %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	return os.WriteFile(dest, body, 0o644)
}

// generateTemplate writes templates/_generated.tpl: a "resources.render"
// aggregate that, for every resource kind in CRDs.yaml, includes the generic
// "resources.generic.renderAll" template defined in templates/_resource.tpl.
func generateTemplate(dir string, entries []entry) error {
	templatesDir := filepath.Join(dir, "templates")
	if err := os.MkdirAll(templatesDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", templatesDir, err)
	}

	var sb strings.Builder
	sb.WriteString("{{/*\nAUTO-GENERATED by build.go from CRDs.yaml. Do not edit manually.\n*/}}\n\n")

	sb.WriteString(`{{- define "resources.render" }}
  {{- $rootContext := .rootContext }}
`)
	for _, e := range entries {
		if e.apiVersion == "" || e.kind == "" {
			return fmt.Errorf("entry %q is missing apiVersion/kind in CRDs.yaml", e.name)
		}

		if e.contentIsSpec {
			fmt.Fprintf(&sb, `  {{- include "resources.generic.renderAll" (dict "rootContext" $rootContext "name" %q "apiVersion" %q "kind" %q) }}
`, e.name, e.apiVersion, e.kind)
		} else {
			fmt.Fprintf(&sb, `  {{- include "resources.generic.renderAll" (dict "rootContext" $rootContext "name" %q "apiVersion" %q "kind" %q "contentIsSpec" false) }}
`, e.name, e.apiVersion, e.kind)
		}
	}
	sb.WriteString("{{- end }}\n")

	dest := filepath.Join(templatesDir, "_generated.tpl")
	fmt.Printf("generating %s\n", dest)
	return os.WriteFile(dest, []byte(sb.String()), 0o644)
}

// parseCRDs is a minimal parser for the restricted YAML shape used by CRDs.yaml:
//
//	crds:
//	  <name>:
//	    url: <value>
//	    apiVersion: <value>
//	    kind: <value>
//	    contentIsSpec: <true|false>   # optional, defaults to true
//
// It avoids pulling in a YAML dependency for this single-purpose script.
func parseCRDs(path string) ([]entry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var entries []entry
	var current *entry

	flush := func() {
		if current != nil {
			entries = append(entries, *current)
			current = nil
		}
	}

	for _, rawLine := range strings.Split(string(data), "\n") {
		line := strings.TrimRight(rawLine, " \t\r")
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}

		indent := len(line) - len(strings.TrimLeft(line, " "))
		trimmed := strings.TrimSpace(line)

		switch {
		case indent == 0:
			// top-level key, e.g. "crds:" — nothing to do.
			continue
		case indent == 2 && strings.HasSuffix(trimmed, ":"):
			flush()
			current = &entry{name: strings.TrimSuffix(trimmed, ":"), contentIsSpec: true}
		case indent == 4 && current != nil:
			key, value, ok := strings.Cut(trimmed, ":")
			if !ok {
				continue
			}
			value = strings.TrimSpace(value)
			switch strings.TrimSpace(key) {
			case "url":
				current.url = value
			case "apiVersion":
				current.apiVersion = value
			case "kind":
				current.kind = value
			case "contentIsSpec":
				current.contentIsSpec = value == "true"
			}
		}
	}
	flush()

	return entries, nil
}
