package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// entry represents one resource kind declared in CRDs.yaml, e.g.:
//
//	configMaps:
//	  url: https://...configmap.json
//	  apiVersion: v1
//	  kind: ConfigMap
//	  contentIsSpec: false
type entry struct {
	name          string
	url           string
	apiVersion    string
	kind          string
	contentIsSpec bool     // defaults to true; set contentIsSpec: false in CRDs.yaml to override
	required      []string // top-level required fields, extracted from the upstream k8s schema
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run() error {
	dir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}

	yamlPath := filepath.Join(dir, "CRDs.yaml")
	entries, err := parseCRDs(yamlPath)
	if err != nil {
		return fmt.Errorf("parse %s: %w", yamlPath, err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("no entries found in %s", yamlPath)
	}

	if err := fetchSchemas(dir, entries); err != nil {
		return err
	}

	if err := generateTemplate(dir, entries); err != nil {
		return err
	}

	if err := generateValuesSchema(dir, entries); err != nil {
		return err
	}

	return nil
}

func fetchSchemas(dir string, entries []entry) error {
	schemaDir := filepath.Join(dir, "schema", "resources")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", schemaDir, err)
	}

	client := &http.Client{Timeout: 30 * time.Second}

	var failed []string
	for i := range entries {
		e := &entries[i]
		if e.url == "" {
			continue
		}
		dest := filepath.Join(schemaDir, e.name+".json")
		fmt.Printf("fetching %s -> %s\n", e.url, dest)
		required, err := fetchAndTransformSchema(client, *e, dest)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  failed: %v\n", err)
			failed = append(failed, e.name)
			continue
		}
		e.required = required
	}

	if len(failed) > 0 {
		return fmt.Errorf("failed to fetch schemas: %s", strings.Join(failed, ", "))
	}
	return nil
}

// fetchAndTransformSchema fetches a kind's full k8s JSON schema from e.url,
// transforms it into the instance schema used for
// .Values.resources.<name>.<id> (see buildInstanceSchema), and writes that
// transformed schema to dest. schema/resources/<name>.json therefore holds
// the ready-to-use instance schema, not the raw upstream k8s schema. The
// instance schema never contains a top-level "required": required fields are
// returned separately so callers can generate template-based validation
// instead (see generateTemplate/resources.generic.requireFields), since
// .Values.resources.<name>.<id> and .Values.defaultValues.<name> share the
// exact same schema and only the merged result must satisfy "required".
func fetchAndTransformSchema(client *http.Client, e entry, dest string) ([]string, error) {
	resp, err := client.Get(e.url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var kindSchema map[string]interface{}
	if err := json.Unmarshal(body, &kindSchema); err != nil {
		return nil, fmt.Errorf("parse fetched schema: %w", err)
	}

	instance, required, err := buildInstanceSchema(kindSchema, e)
	if err != nil {
		return nil, err
	}

	out, err := json.MarshalIndent(instance, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal instance schema: %w", err)
	}
	out = append(out, '\n')

	if err := os.WriteFile(dest, out, 0o644); err != nil {
		return nil, err
	}
	return required, nil
}

// generateTemplate writes templates/_generated.tpl: a "resources.render"
// aggregate that, for every resource kind in CRDs.yaml, includes the generic
// "resources.generic.renderAll" template defined in templates/_resource.tpl.
func generateTemplate(dir string, entries []entry) error {
	templatesDir := filepath.Join(dir, "templates")
	if err := os.MkdirAll(templatesDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", templatesDir, err)
	}

	var sb strings.Builder
	sb.WriteString("{{/*\nAUTO-GENERATED by build.go from CRDs.yaml. Do not edit manually.\n*/}}\n\n")

	sb.WriteString(`{{- define "resources.render" }}
  {{- $rootContext := .rootContext }}
`)
	for _, e := range entries {
		if e.apiVersion == "" || e.kind == "" {
			return fmt.Errorf("entry %q is missing apiVersion/kind in CRDs.yaml", e.name)
		}

		args := []string{fmt.Sprintf(`"rootContext" $rootContext "name" %q "apiVersion" %q "kind" %q`, e.name, e.apiVersion, e.kind)}
		if !e.contentIsSpec {
			args = append(args, `"contentIsSpec" false`)
		}
		if len(e.required) > 0 {
			quoted := make([]string, len(e.required))
			for i, r := range e.required {
				quoted[i] = fmt.Sprintf("%q", r)
			}
			args = append(args, fmt.Sprintf(`"required" (list %s)`, strings.Join(quoted, " ")))
		}
		fmt.Fprintf(&sb, `  {{- include "resources.generic.renderAll" (dict %s) }}
`, strings.Join(args, " "))
	}
	sb.WriteString("{{- end }}\n")

	dest := filepath.Join(templatesDir, "_generated.tpl")
	fmt.Printf("generating %s\n", dest)
	return os.WriteFile(dest, []byte(sb.String()), 0o644)
}

// metadataSchemaProperties are the well-known fields handled by
// resources.generic.computeMetadata / resources.generic.computeName. They're
// injected into every resource kind's instance schema, and take precedence
// over any same-named property coming from the kind's own k8s JSON schema.
func metadataSchemaProperties() map[string]interface{} {
	return map[string]interface{}{
		"nameOverride": map[string]interface{}{
			"type":        "string",
			"description": "Replaces just the id part of the computed resource name (<Release.Name>-<id>).",
		},
		"fullNameOverride": map[string]interface{}{
			"type":        "string",
			"description": "Replaces the entire computed resource name, ignoring the release name and id.",
		},
		"namespace": map[string]interface{}{
			"type":        "string",
			"description": "metadata.namespace for this resource. Defaults to the release namespace.",
		},
		"labels": map[string]interface{}{
			"type":                 "object",
			"description":          "metadata.labels for this resource.",
			"additionalProperties": map[string]interface{}{"type": "string"},
		},
		"annotations": map[string]interface{}{
			"type":                 "object",
			"description":          "metadata.annotations for this resource.",
			"additionalProperties": map[string]interface{}{"type": "string"},
		},
	}
}

// buildInstanceSchema builds the JSON schema for one entry under
// .Values.resources.<name>.<id> (or .Values.defaultValues.<name>), by
// extracting the relevant portion of the kind's full k8s JSON schema:
//   - contentIsSpec: true  -> the schema's own top-level "spec" property
//   - contentIsSpec: false -> the schema's top-level properties, minus
//     apiVersion/kind/metadata/status
//
// and merging in the well-known metadata fields (labels, annotations,
// namespace, nameOverride, fullNameOverride).
//
// The returned schema never has a top-level "required": since
// .Values.resources.<name>.<id> and .Values.defaultValues.<name> share this
// exact schema (a defaultValues entry is a partial overlay and should not be
// forced to satisfy "required" on its own), any top-level "required" found in
// the upstream k8s schema is extracted and returned separately instead, so it
// can be enforced on the MERGED resource via generated template validation
// (see generateTemplate and resources.generic.requireFields).
func buildInstanceSchema(kindSchema map[string]interface{}, e entry) (map[string]interface{}, []string, error) {
	var instance map[string]interface{}
	if e.contentIsSpec {
		props, _ := kindSchema["properties"].(map[string]interface{})
		spec, _ := props["spec"].(map[string]interface{})
		if spec == nil {
			return nil, nil, fmt.Errorf("%s: expected top-level \"spec\" property in schema", e.name)
		}
		instance = spec
	} else {
		props, _ := kindSchema["properties"].(map[string]interface{})
		contentProps := map[string]interface{}{}
		for k, v := range props {
			if k == "apiVersion" || k == "kind" || k == "metadata" || k == "status" {
				continue
			}
			contentProps[k] = v
		}
		instance = map[string]interface{}{
			"type":       "object",
			"properties": contentProps,
		}
		if req, ok := kindSchema["required"].([]interface{}); ok {
			var filtered []interface{}
			for _, r := range req {
				if s, _ := r.(string); s != "apiVersion" && s != "kind" && s != "metadata" && s != "status" {
					filtered = append(filtered, r)
				}
			}
			if len(filtered) > 0 {
				instance["required"] = filtered
			}
		}
	}

	var required []string
	if req, ok := instance["required"].([]interface{}); ok {
		for _, r := range req {
			if s, _ := r.(string); s != "" {
				required = append(required, s)
			}
		}
	}
	delete(instance, "required")

	mergedProps := map[string]interface{}{}
	if p, ok := instance["properties"].(map[string]interface{}); ok {
		for k, v := range p {
			mergedProps[k] = v
		}
	}
	for k, v := range metadataSchemaProperties() {
		mergedProps[k] = v
	}
	instance["properties"] = mergedProps
	instance["type"] = "object"

	return instance, required, nil
}

// generateValuesSchema writes schema/values.schema.json: a JSON Schema
// describing .Values.resources.<kind>.<id> and .Values.defaultValues.<kind>.
// Each kind's instance schema lives in schema/resources/<name>.json (written
// by fetchAndTransformSchema) and has no top-level "required" (see
// buildInstanceSchema), so both .Values.resources.<kind> and
// .Values.defaultValues.<kind> can safely $ref that same single file -
// required-field validation on the merged resource is instead generated
// into templates/_generated.tpl (see resources.generic.requireFields).
//
// NOTE: this is intentionally NOT written to the chart root as
// values.schema.json yet (Helm only auto-validates that exact path), since
// Helm's schema validator doesn't resolve cross-file "$ref" the way we need
// here. Wiring it up as the chart's actual values.schema.json (inlining the
// referenced schemas, or otherwise) is deferred to later.
func generateValuesSchema(dir string, entries []entry) error {
	resourcesProps := map[string]interface{}{}
	defaultValuesProps := map[string]interface{}{}

	for _, e := range entries {
		resourcesProps[e.name] = map[string]interface{}{
			"type":                 "object",
			"description":          fmt.Sprintf("%s instances, keyed by id.", e.kind),
			"additionalProperties": map[string]interface{}{"$ref": "./resources/" + e.name + ".json"},
		}

		defaultValuesProps[e.name] = map[string]interface{}{"$ref": "./resources/" + e.name + ".json"}
	}

	schema := map[string]interface{}{
		"$schema": "https://json-schema.org/draft-07/schema#",
		"type":    "object",
		"properties": map[string]interface{}{
			"resources": map[string]interface{}{
				"type":       "object",
				"properties": resourcesProps,
			},
			"defaultValues": map[string]interface{}{
				"type":       "object",
				"properties": defaultValuesProps,
			},
		},
	}

	out, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal values.schema.json: %w", err)
	}
	out = append(out, '\n')

	dest := filepath.Join(dir, "schema", "values.schema.json")
	fmt.Printf("generating %s\n", dest)
	return os.WriteFile(dest, out, 0o644)
}

// parseCRDs is a minimal parser for the restricted YAML shape used by CRDs.yaml:
//
//	crds:
//	  <name>:
//	    url: <value>
//	    apiVersion: <value>
//	    kind: <value>
//	    contentIsSpec: <true|false>   # optional, defaults to true
//
// It avoids pulling in a YAML dependency for this single-purpose script.
func parseCRDs(path string) ([]entry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var entries []entry
	var current *entry

	flush := func() {
		if current != nil {
			entries = append(entries, *current)
			current = nil
		}
	}

	for _, rawLine := range strings.Split(string(data), "\n") {
		line := strings.TrimRight(rawLine, " \t\r")
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}

		indent := len(line) - len(strings.TrimLeft(line, " "))
		trimmed := strings.TrimSpace(line)

		switch {
		case indent == 0:
			// top-level key, e.g. "crds:" — nothing to do.
			continue
		case indent == 2 && strings.HasSuffix(trimmed, ":"):
			flush()
			current = &entry{name: strings.TrimSuffix(trimmed, ":"), contentIsSpec: true}
		case indent == 4 && current != nil:
			key, value, ok := strings.Cut(trimmed, ":")
			if !ok {
				continue
			}
			value = strings.TrimSpace(value)
			switch strings.TrimSpace(key) {
			case "url":
				current.url = value
			case "apiVersion":
				current.apiVersion = value
			case "kind":
				current.kind = value
			case "contentIsSpec":
				current.contentIsSpec = value == "true"
			}
		}
	}
	flush()

	return entries, nil
}
