crds:
  configMaps:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/configmap.json
    apiVersion: v1
    kind: ConfigMap
    contentIsSpec: false
  secrets:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/secret.json
    apiVersion: v1
    kind: Secret
    contentIsSpec: false
  horizontalPodAutoscalers:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/horizontalpodautoscaler-autoscaling-v2.json
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
  services:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/service-v1.json
    apiVersion: v1
    kind: Service
  persistentVolumes:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/persistentvolume-v1.json
    apiVersion: v1
    kind: PersistentVolume
  persistentVolumeClaims:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/persistentvolumeclaim-v1.json
    apiVersion: v1
    kind: PersistentVolumeClaim
  namespaces:
    url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/namespace-v1.json
    apiVersion: v1
    kind: Namespace
