resources:
  configMaps:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.ConfigMap
    apiVersion: v1
    kind: ConfigMap
    contentIsSpec: false
    transformer:
      stringifyFields:
        fields:
          - data
  secrets:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.Secret
    apiVersion: v1
    kind: Secret
    contentIsSpec: false
  horizontalPodAutoscalers:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__autoscaling__v2_openapi.json
    component: io.k8s.api.autoscaling.v2.HorizontalPodAutoscaler
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
  services:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.Service
    apiVersion: v1
    kind: Service
  persistentVolumes:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.PersistentVolume
    apiVersion: v1
    kind: PersistentVolume
  persistentVolumeClaims:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.PersistentVolumeClaim
    apiVersion: v1
    kind: PersistentVolumeClaim
  namespaces:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.Namespace
    apiVersion: v1
    kind: Namespace
  deployments:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__apps__v1_openapi.json
    component: io.k8s.api.apps.v1.Deployment
    apiVersion: apps/v1
    kind: Deployment
    transformer:
      arraysToMaps:
        ignore:
          - template.spec.containers.command
          - template.spec.containers.args
          - template.spec.initContainers.command
          - template.spec.initContainers.args
  statefulSets:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__apps__v1_openapi.json
    component: io.k8s.api.apps.v1.StatefulSet
    apiVersion: apps/v1
    kind: StatefulSet
    transformer:
      arraysToMaps:
        ignore:
          - template.spec.containers.command
          - template.spec.containers.args
          - template.spec.initContainers.command
          - template.spec.initContainers.args
  daemonSets:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__apps__v1_openapi.json
    component: io.k8s.api.apps.v1.DaemonSet
    apiVersion: apps/v1
    kind: DaemonSet
    transformer:
      arraysToMaps:
        ignore:
          - template.spec.containers.command
          - template.spec.containers.args
          - template.spec.initContainers.command
          - template.spec.initContainers.args
  cronJobs:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__batch__v1_openapi.json
    component: io.k8s.api.batch.v1.CronJob
    apiVersion: batch/v1
    kind: CronJob
    transformer:
      arraysToMaps:
        ignore:
          - jobTemplate.spec.template.spec.containers.command
          - jobTemplate.spec.template.spec.containers.args
          - jobTemplate.spec.template.spec.initContainers.command
          - jobTemplate.spec.template.spec.initContainers.args
  jobs:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__batch__v1_openapi.json
    component: io.k8s.api.batch.v1.Job
    apiVersion: batch/v1
    kind: Job
    transformer:
      arraysToMaps:
        ignore:
          - template.spec.containers.command
          - template.spec.containers.args
          - template.spec.initContainers.command
          - template.spec.initContainers.args
  serviceAccounts:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/api__v1_openapi.json
    component: io.k8s.api.core.v1.ServiceAccount
    apiVersion: v1
    kind: ServiceAccount
    contentIsSpec: false
  roles:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__rbac.authorization.k8s.io__v1_openapi.json
    component: io.k8s.api.rbac.v1.Role
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    contentIsSpec: false
  roleBindings:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__rbac.authorization.k8s.io__v1_openapi.json
    component: io.k8s.api.rbac.v1.RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    contentIsSpec: false
  clusterRoles:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__rbac.authorization.k8s.io__v1_openapi.json
    component: io.k8s.api.rbac.v1.ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    contentIsSpec: false
  clusterRoleBindings:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__rbac.authorization.k8s.io__v1_openapi.json
    component: io.k8s.api.rbac.v1.ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    contentIsSpec: false
  podDisruptionBudgets:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__policy__v1_openapi.json
    component: io.k8s.api.policy.v1.PodDisruptionBudget
    apiVersion: policy/v1
    kind: PodDisruptionBudget
  ingresses:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__networking.k8s.io__v1_openapi.json
    component: io.k8s.api.networking.v1.Ingress
    apiVersion: networking.k8s.io/v1
    kind: Ingress
  networkPolicies:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__networking.k8s.io__v1_openapi.json
    component: io.k8s.api.networking.v1.NetworkPolicy
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
  gateways:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    crdVersion: v1
  gatewayClasses:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: GatewayClass
    crdVersion: v1
  httpRoutes:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    crdVersion: v1
  grpcRoutes:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: GRPCRoute
    crdVersion: v1
  referenceGrants:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    crdVersion: v1beta1
  tcpRoutes:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_tcproutes.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: TCPRoute
    crdVersion: v1
  tlsRoutes:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_tlsroutes.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: TLSRoute
    crdVersion: v1
  udpRoutes:
    url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_udproutes.yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: UDPRoute
    crdVersion: v1
  storageClasses:
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/v3/apis__storage.k8s.io__v1_openapi.json
    component: io.k8s.api.storage.v1.StorageClass
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    contentIsSpec: false
  volumeSnapshotClasses:
    url: https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshotClass
    crdVersion: v1
    contentIsSpec: false
  sealedSecrets:
    url: https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/main/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    crdVersion: v1alpha1
  clusterPolicies:
    url: https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno/kyverno.io_clusterpolicies.yaml
    apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    crdVersion: v1
  recurringJobs:
    url: https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
    apiVersion: longhorn.io/v1beta2
    kind: RecurringJob
    crdVersion: v1beta2
  settings:
    url: https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
    apiVersion: longhorn.io/v1beta2
    kind: Setting
    crdVersion: v1beta2
    contentIsSpec: false
  routes:
    url: https://raw.githubusercontent.com/openshift/api/master/route/v1/zz_generated.crd-manifests/routes.crd.yaml
    apiVersion: route.openshift.io/v1
    kind: Route
    crdVersion: v1
  helmReleases:
    url: https://raw.githubusercontent.com/fluxcd/helm-controller/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    crdVersion: v2
  kustomizations:
    url: https://raw.githubusercontent.com/fluxcd/kustomize-controller/main/config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    crdVersion: v1
  gitRepositories:
    url: https://raw.githubusercontent.com/fluxcd/source-controller/main/config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    crdVersion: v1
  helmRepositories:
    url: https://raw.githubusercontent.com/fluxcd/source-controller/main/config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: HelmRepository
    crdVersion: v1
  ociRepositories:
    url: https://raw.githubusercontent.com/fluxcd/source-controller/main/config/crd/bases/source.toolkit.fluxcd.io_ocirepositories.yaml
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    crdVersion: v1
  imageRepositories:
    url: https://raw.githubusercontent.com/fluxcd/image-reflector-controller/main/config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
    apiVersion: image.toolkit.fluxcd.io/v1
    kind: ImageRepository
    crdVersion: v1
  imagePolicies:
    url: https://raw.githubusercontent.com/fluxcd/image-reflector-controller/main/config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
    apiVersion: image.toolkit.fluxcd.io/v1
    kind: ImagePolicy
    crdVersion: v1
  certificates:
    url: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/cert-manager.io_certificates.yaml
    apiVersion: cert-manager.io/v1
    kind: Certificate
    crdVersion: v1
  certificateRequests:
    url: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/cert-manager.io_certificaterequests.yaml
    apiVersion: cert-manager.io/v1
    kind: CertificateRequest
    crdVersion: v1
  issuers:
    url: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/cert-manager.io_issuers.yaml
    apiVersion: cert-manager.io/v1
    kind: Issuer
    crdVersion: v1
  clusterIssuers:
    url: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/cert-manager.io_clusterissuers.yaml
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    crdVersion: v1
  orders:
    url: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/acme.cert-manager.io_orders.yaml
    apiVersion: acme.cert-manager.io/v1
    kind: Order
    crdVersion: v1
  challenges:
    url: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/acme.cert-manager.io_challenges.yaml
    apiVersion: acme.cert-manager.io/v1
    kind: Challenge
    crdVersion: v1
  clusters:
    url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_clusters.yaml
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    crdVersion: v1
  scheduledBackups:
    url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
    apiVersion: postgresql.cnpg.io/v1
    kind: ScheduledBackup
    crdVersion: v1
  secretStores:
    url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crds/bases/external-secrets.io_secretstores.yaml
    apiVersion: external-secrets.io/v1
    kind: SecretStore
    crdVersion: v1
  alerts:
    url: https://raw.githubusercontent.com/fluxcd/notification-controller/main/config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
    apiVersion: notification.toolkit.fluxcd.io/v1beta3
    kind: Alert
    crdVersion: v1beta3
  receivers:
    url: https://raw.githubusercontent.com/fluxcd/notification-controller/main/config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
    apiVersion: notification.toolkit.fluxcd.io/v1
    kind: Receiver
    crdVersion: v1
  providers:
    url: https://raw.githubusercontent.com/fluxcd/notification-controller/main/config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
    apiVersion: notification.toolkit.fluxcd.io/v1beta3
    kind: Provider
    crdVersion: v1beta3
  stringSecrets:
    url: https://raw.githubusercontent.com/mittwald/kubernetes-secret-generator/master/deploy/crds/secretgenerator.mittwald.de_stringsecrets_crd.yaml
    apiVersion: secretgenerator.mittwald.de/v1alpha1
    kind: StringSecret
    crdVersion: v1alpha1
  ingressRouteTCPs:
    url: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/reference/dynamic-configuration/traefik.io_ingressroutetcps.yaml
    apiVersion: traefik.io/v1alpha1
    kind: IngressRouteTCP
    crdVersion: v1alpha1
  middlewares:
    url: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/reference/dynamic-configuration/traefik.io_middlewares.yaml
    apiVersion: traefik.io/v1alpha1
    kind: Middleware
    crdVersion: v1alpha1
  networkAttachmentDefinitions:
    url: https://raw.githubusercontent.com/k8snetworkplumbingwg/network-attachment-definition-client/master/artifacts/networks-crd.yaml
    apiVersion: k8s.cni.cncf.io/v1
    kind: NetworkAttachmentDefinition
    crdVersion: v1
  serviceMonitors:
    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    crdVersion: v1
  validatingPolicies:
    url: https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/policies.kyverno.io/policies.kyverno.io_validatingpolicies.yaml
    apiVersion: policies.kyverno.io/v1
    kind: ValidatingPolicy
    crdVersion: v1
  verticalPodAutoscalers:
    url: https://raw.githubusercontent.com/kubernetes/autoscaler/master/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
    apiVersion: autoscaling.k8s.io/v1
    kind: VerticalPodAutoscaler
    crdVersion: v1
