{{/*
AUTO-GENERATED by build.go from CRDs.yaml. Do not edit manually.
*/}}

{{- define "resources.configMaps.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "configMaps" "apiVersion" "v1" "kind" "ConfigMap" "contentFields" (list "data" "binaryData")) }}
{{- end }}

{{- define "resources.secrets.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "secrets" "apiVersion" "v1" "kind" "Secret" "contentFields" (list "stringData")) }}
{{- end }}

{{- define "resources.horizontalPodAutoscalers.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "horizontalPodAutoscalers" "apiVersion" "autoscaling/v2" "kind" "HorizontalPodAutoscaler" "contentFields" (list "spec")) }}
{{- end }}

{{- define "resources.services.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "services" "apiVersion" "v1" "kind" "Service" "contentFields" (list "spec")) }}
{{- end }}

{{- define "resources.render" }}
  {{- $rootContext := .rootContext }}
  {{- include "resources.configMaps.render" (dict "rootContext" $rootContext) }}
  {{- include "resources.secrets.render" (dict "rootContext" $rootContext) }}
  {{- include "resources.horizontalPodAutoscalers.render" (dict "rootContext" $rootContext) }}
  {{- include "resources.services.render" (dict "rootContext" $rootContext) }}
{{- end }}
