{{/*
AUTO-GENERATED by build.go from CRDs.yaml. Do not edit manually.
*/}}

{{- define "resources.render" }}
  {{- $rootContext := .rootContext }}
  {{- include "resources.generic.renderAll" (dict "rootContext" $rootContext "name" "configMaps" "apiVersion" "v1" "kind" "ConfigMap" "contentIsSpec" false) }}
  {{- include "resources.generic.renderAll" (dict "rootContext" $rootContext "name" "secrets" "apiVersion" "v1" "kind" "Secret" "contentIsSpec" false) }}
  {{- include "resources.generic.renderAll" (dict "rootContext" $rootContext "name" "horizontalPodAutoscalers" "apiVersion" "autoscaling/v2" "kind" "HorizontalPodAutoscaler" "required" (list "scaleTargetRef" "maxReplicas")) }}
  {{- include "resources.generic.renderAll" (dict "rootContext" $rootContext "name" "services" "apiVersion" "v1" "kind" "Service") }}
{{- end }}
