{{/*
AUTO-GENERATED by build.go from CRDs.yaml. Do not edit manually.
*/}}

{{- define "resources.configMaps.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "configMaps" "apiVersion" "v1" "kind" "ConfigMap" "contentField" "data") }}
{{- end }}

{{- define "resources.secrets.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "secrets" "apiVersion" "v1" "kind" "Secret" "contentField" "stringData") }}
{{- end }}

{{- define "resources.horizontalPodAutoscalers.render" }}
  {{- include "resources.generic.render" (dict "rootContext" .rootContext "name" "horizontalPodAutoscalers" "apiVersion" "autoscaling/v2" "kind" "HorizontalPodAutoscaler" "contentField" "spec") }}
{{- end }}

{{- define "resources.render" }}
  {{- $rootContext := .rootContext }}
  {{- include "resources.configMaps.render" (dict "rootContext" $rootContext) }}
  {{- include "resources.secrets.render" (dict "rootContext" $rootContext) }}
  {{- include "resources.horizontalPodAutoscalers.render" (dict "rootContext" $rootContext) }}
{{- end }}
