apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 10m
  timeout: 2m
  chart:
    spec:
      chart: descheduler
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
  rollback:
    cleanupOnFail: true
