---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: coredns
      version: 1.45.0
      sourceRef:
        kind: HelmRepository
        name: coredns
  values:
    fullnameOverride: coredns
    image:
      repository: mirror.gcr.io/coredns/coredns
    replicaCount: 2
    k8sAppLabelOverride: kube-dns
    serviceAccount:
      create: true
    service:
      name: kube-dns
      clusterIP: 172.16.42.10
    servers:
      - zones:
          - zone: .
            scheme: dns://
            use_tcp: true
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
          - name: autopath
            parameters: "@kubernetes"
          - name: forward
            parameters: . /etc/resolv.conf
            configBlock: |-
              max_concurrent 1000
          - name: cache
            configBlock: |-
              prefetch 30
#              serve_stale
          - name: loop
          - name: reload
          - name: loadbalance
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: log
            configBlock: |-
              class error
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
