---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-release-usesGlobalMetadataOnly
  namespace: shared-ns
  labels:
    org: acme
  annotations:
    managed-by: base-resources
stringData:
  key: value3
---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-overridesDefault
  namespace: shared-ns
  labels:
    app: custom-app
    org: acme
    team: platform
  annotations:
    managed-by: base-resources
data:
  key: value2
---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-overridesGlobalNamespace
  namespace: custom-ns
  labels:
    app: shared-default
    org: acme
    team: platform
  annotations:
    managed-by: base-resources
data:
  key: value4
---
# Source: resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-usesDefaultOnly
  namespace: shared-ns
  labels:
    app: shared-default
    org: acme
    team: platform
  annotations:
    managed-by: base-resources
data:
  key: value1
