# yaml-language-server: $schema=../values.schema.json

defaults:
  metadata:
    labels:
      org: acme
    annotations:
      managed-by: base-resources
  resources:
    configMaps:
      labels:
        app: shared-default
        team: platform

resources:
  configMaps:
    usesDefaultOnly:
      data:
        key: value1
    overridesDefault:
      labels:
        app: custom-app
      data:
        key: value2
  secrets:
    usesGlobalMetadataOnly:
      stringData:
        key: value3
