---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: totally-custom-name
  namespace: default
data:
  a: b
---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-normal
  namespace: default
data:
  a: b
