---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
data:
  a: b
kind: ConfigMap
metadata:
  name: test-release
  namespace: default
---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-release
  namespace: default
spec:
  ports:
  - port: 80
  selector:
    app: x
