# yaml-language-server: $schema=../schema/values.schema.json

resources:
  clusterPolicies:
    main:
      rules:
        - name: set-image-pull-policy
          match:
            any:
              - resources:
                  kinds:
                    - Pod
          mutate:
            patchStrategicMerge:
              spec:
                containers:
                  - (image): "*"
                    imagePullPolicy: "IfNotPresent"
