# yaml-language-server: $schema=../schema/values.schema.json

resources:
  clusterIssuers:
    main:
      acme:
        email: admin@example.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-prod
        solvers:
          - http01:
              ingress:
                class: traefik
