---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
data:
  key: value
  structured: |-
    foo: bar
    nested:
    - a
    - b
kind: ConfigMap
metadata:
  name: test-release
  namespace: default
