---
# Source: base-resources-test/templates/loader.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-release
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: myimage:latest
        name: myapp
