---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-defaultEnabled
  namespace: default
data:
  main: cm
---
# Source: base-resources-test/templates/loader.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-release-explicitlyEnabled
  namespace: default
data:
  main: cm
