---
# Source: base-resources-test/templates/loader.yaml
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: test-release
  namespace: default
spec:
  imageRepositoryRef:
    name: main
  policy:
    semver:
      range: '>=1.0.0'
