# yaml-language-server: $schema=../schema/values.schema.json

resources:
  middlewares:
    body-limit-10g:
      buffering:
        maxRequestBodyBytes: 10000000000
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
