# yaml-language-server: $schema=../values.schema.json

resources:
  ociRepositories:
    main:
      interval: 5m
      url: oci://ghcr.io/stefanprodan/manifests/podinfo
      ref:
        tag: latest
