---
# Source: base-resources-test/templates/loader.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-release
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: myapp
