# yaml-language-server: $schema=../schema/values.schema.json

resources:
  recurringJobs:
    main:
      cron: 0 4 * * *
      task: backup
      groups:
        - default
      retain: 2
      concurrency: 1
