---
# Source: base-resources-test/templates/loader.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: test-release
  namespace: default
parameters:
  dataLocality: strict-local
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "60"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
