apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lldap-postgresql
  namespace: lldap
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: lldap-postgresql
