apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap-postgresql
  namespace: lldap
spec:
  instances: 2
  # https://cloudnative-pg.io/docs/1.28/ssl_connections
  postgresql:
    pg_hba:
      - hostssl app all all cert

  certificates:
    clientCASecret: lldap-postgresql-ca
    # replication is required so cnpg do not look for ca.key in the clientCASecret, which is not the format of cert-manager
    replicationTLSSecret: lldap-postgresql-replication-tls
    serverTLSSecret: lldap-postgresql-tls
    serverCASecret: lldap-postgresql-tls

  storage:
    storageClass: longhorn-single-local-replica
    size: 1Gi

#  bootstrap:
#    recovery:
#      volumeSnapshots:
#        storage:
#          name: <snapshot name>
#          kind: VolumeSnapshot
#          apiGroup: snapshot.storage.k8s.io
# OR
#      backup:
#        name: backup-example

  backup:
    retentionPolicy: "60d"
    volumeSnapshot:
      className: longhorn-backup-incremental
      snapshotOwnerReference: backup # removing the Backup object, removes the VolumeSnapshot
