apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lldap-postgresql
  namespace: lldap
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self # removing the schedule, removes the Backup object, which may or not remove the VolumeSnapshot object depending on the cluster's setup
  immediate: true
  method: volumeSnapshot
  cluster:
    name: lldap-postgresql
