apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-postgresql-app
  namespace: lldap
spec:
  secretName: lldap-postgresql-app-tls
  usages:
    - client auth
  commonName: app
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
