apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap-postgresql
  namespace: lldap
spec:
  instances: 1

  # https://cloudnative-pg.io/docs/1.28/ssl_connections
  # kubectl cnpg certificate -n lldap lldap-postgresql-app-cert --cnpg-cluster lldap-postgresql --cnpg-user app
  postgresql:
    pg_hba:
      - hostssl app all all cert

  certificates:
    clientCASecret: lldap-postgresql-replication-tls
    replicationTLSSecret: lldap-postgresql-replication-tls
    serverTLSSecret: lldap-postgresql-tls
    serverCASecret: lldap-postgresql-tls

  storage:
    storageClass: longhorn-single-local-replica
    size: 1Gi

  backup:
    retentionPolicy: "60d"
    barmanObjectStore:
      destinationPath: s3://lldap-postgresql-backup
      endpointURL: https://lldap-postgresql-backup.lldap.svc.cluster.local
      endpointCA:
        name: lldap-postgresql-backup-tls
        key: ca.crt
      s3Credentials:
        accessKeyId:
          name: lldap-postgresql-backup
          key: MINIO_ROOT_USER
        secretAccessKey:
          name: lldap-postgresql-backup
          key: MINIO_ROOT_PASSWORD
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lldap-postgresql
  namespace: lldap
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: lldap-postgresql
