kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-local-replica
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "60" # 1h
  fsType: "ext4"
  dataLocality: "strict-local"
  recurringJobSelector: '[
      {
        "name":"single-local-replica",
        "isGroup":true
      }
    ]'
