apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    # memory leak and validator fail in 1.11.0
    # https://github.com/longhorn/longhorn/releases/tag/v1.11.0
    image:
      longhorn:
        manager:
          tag: v1.11.0-hotfix-1
        instanceManager:
            tag: v1.11.0-hotfix-1
    preUpgradeChecker:
      jobEnabled: false
      upgradeVersionCheck: false


    enablePSP: false

    defaultSettings:
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      nodeDrainPolicy: always-allow

    defaultBackupStore:
      backupTarget: cifs://backupstore/backupstore
      backupTargetCredentialSecret: backupstore
      pollInterval: 180

    ingress:
      enabled: true
      host: longhorn.${BCL_GLOBAL_DOMAIN}
      tls: true
      annotations:
        kubernetes.io/tls-acme: true
        traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
