apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  # move that to global
  interval: 10m
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    args:
      - --kubelet-insecure-tls
      - --metric-resolution=10s
      - --kubelet-request-timeout=2s

    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
