apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 60m
  chart:
    spec:
      chart: renovate
      version: 45.83.0
      sourceRef:
        kind: HelmRepository
        name: renovate
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    apiVersionOverrides: 
      cronjob: batch/v1

    dind:
      enabled: true
      slim:
        enabled: false

    cronjob: 
      schedule: '0 10 * * *'
      suspend: false
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 5
      successfulJobsHistoryLimit: 3
      backoffLimit: 0

    ssh_config:
      enabled: true
      existingSecret: renovate-ssh

    existingSecret: renovate
    env:
     LOG_LEVEL: DEBUG

    renovate:
      config: |
        {
          "platform": "gitea",
          "endpoint": "http://gitea-http.gitea:3000/api/v1",
          "repositories": ["${BCL_GLOBAL_NAME}/infra"],
          "detectHostRulesFromEnv": true,
          "printConfig": false,
          "requireConfig": "optional",
        }
