# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rutorrent
  namespace: rutorrent
spec:
  interval: 60m
  timeout: 1m
  chart:
    spec:
      chart: base-template
      version: 1.250501.709-Heffe9b6
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: flux-system
  rollback:
    cleanupOnFail: true
  values:
    mainWorkload:
      type: singleton
      pod:
        gracefulShutdownTimeout: 10s
        dnsConfig:
          nameservers:
          - 8.8.8.8
          - 8.8.4.4          

      service:
        ports:
          http:
            port: 8080

      container:
        securityContext:
#          runAsUser: 911
#          runAsGroup: 911
          runAsNonRoot: false
          readOnlyRootFilesystem: false
        env:
          RUTORRENT_PORT: "8080"
        image:
          repository: ghcr.io/crazy-max/rtorrent-rutorrent
          tag: 5.2.10-0.16.4
        command: ['sh', '-e', '-c']
        args:
        - |
          echo "Starting"

          echo "Waiting for vpn ip"
          while [ "$(ip a | grep inet | wc -l)" == "2" ]; do
            sleep 10
          done

          echo "Checking public ip before start"
          while true; do
            IP=$(curl https://ifconfig.me/ip)
            F="1"
            if [ "$IP" == "$(dig +short 1.lmr.io)" ] || [ "$IP" == "$(dig +short 2.lmr.io)" ]; then
              F="0"
            fi
            if [ "$F" == "1" ]; then
              break
            fi
            sleep 10
          done

          /init &
          
          echo "Checking public ip"
          LMR1=$(dig +short 1.lmr.io)
          LMR2=$(dig +short 2.lmr.io)
          while true; do
            IP=$(curl --silent ifconfig.me/ip || true)
            if [ "$IP" == "$LMR1" ] || [ "$IP" == "$LMR2" ] || [ "$IP" == "" ]; then
              echo "###### lost 1"
              sleep 31
              IP=$(curl --silent ifconfig.co || true)
              if [ "$IP" == "$LMR1" ] || [ "$IP" == "$LMR2" ] || [ "$IP" == "" ]; then
                echo "###### lost 2"
                sleep 32
                LMR1=$(dig +short 1.lmr.io)
                LMR2=$(dig +short 2.lmr.io)
                IP=$(curl --silent icanhazip.com || true)
                if [ "$IP" == "$LMR1" ] || [ "$IP" == "$LMR2" ] || [ "$IP" == "" ]; then
                  echo "###### lost 3"
                  sleep 60
                  LMR1=$(dig +short 1.lmr.io)
                  LMR2=$(dig +short 2.lmr.io)
                  IP=$(curl --silent icanhazip.com || true)
                  if [ "$IP" == "$LMR1" ] || [ "$IP" == "$LMR2" ] || [ "$IP" == "" ]; then
                    echo "###### Not on VPN or cannot check"
                    killall -9 rtorrent
                    exit 1
                  fi
                fi
              fi
            fi
            sleep 10
          done

      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-body-limit-2g@kubernetescrd,traefik-authelia@kubernetescrd
        hosts:
        - host: rutorrent.${BCL_GLOBAL_DOMAIN}
          paths:
          - service:
              name: rutorrent
              port: 8080
            path: /
        tls:
        - hosts:
          - rutorrent.${BCL_GLOBAL_DOMAIN}
          secretName: tls-rutorrent

      volumes:
        videos:
          type: hostPath
          hostPath: /data/Videos
          path: /host-data/Videos
        downloads:
          type: hostPath
          hostPath: /data/Caches/rutorrent-downloads
          path: /downloads
        conf:
          type: secret
          name: rutorrent
          defaultMode: 0400
          containers:
            vpn:
              path: /etc/wireguard
        data:
          type: persistentVolumeClaim
          containers:
            main:
              path: /data

    resources:
      persistentVolumeClaims:
        data:
          storageClass: rutorrent
      persistentVolumes:
        data:
          storageClassName: rutorrent
          csi:
            driver: driver.longhorn.io
            volumeHandle: rutorrent

      controllers:
        main:
          containers:
#            move:
#              image:
#                repository: gitea.lmr.io/lmr/alpine-backup-tools
#                tag: 1.250323.1327-h9c5ad5b8
#              command: [ sh, -e, -c ]
#              securityContext:
#                runAsNonRoot: false
#              args:
#              - |
#                function fmove {
#                    echo ">> Setting rights"
#                    chown -R 911:911 /downloads/complete2
#                    echo ">> Checksum"
#                    /tmp/checksum -c /config/checksum.yaml set /downloads/complete2
#                    echo ">> Rsync"
#                    rsync -a --remove-source-files -K /downloads/complete2/ /downloads/shortcut/
#                    echo ">> Clean folders"
#                    find /downloads/complete2/ -mindepth 1 -type d -empty -delete
#                }
#
#                mkdir -p /downloads/shortcut
#
#                [ -L /downloads/shortcut/tv ] || ln -s /target/video/tv/ /downloads/shortcut/tv
#                [ -L /downloads/shortcut/movie ] || ln -s /target/video/movie/ /downloads/shortcut/movie
#                [ -L /downloads/shortcut/anime ] || ln -s /target/video/anime/ /downloads/shortcut/anime
#                [ -L /downloads/shortcut/music ] || ln -s /target/audio/music/ /downloads/shortcut/music
#
#                wget https://github.com/n0rad/go-checksum/releases/download/v0.1/checksum-linux-amd64.tar.gz -O - | tar -xz --strip 1 -C /tmp
#                mkdir -p /downloads/complete /downloads/complete2
#                while true; do
#                  if ! [ -n "$(find /downloads/complete -prune -empty 2>/dev/null)" ]; then
#                    echo "There is something to do"
#                    fmove
#                    mv /downloads/complete/* /downloads/complete2/
#                    fmove
#                    echo "Done"
#                  fi
#                  sleep 60
#                done
            vpn:
              image:
                repository: gitea.lmr.io/lmr/alpine-wireguard
                tag: 1.250323.1422-h9c5ad5b8
              securityContext:
                privileged: true
                allowPrivilegeEscalation: true
                runAsNonRoot: false
              command: [ sh, -x, -e, -c ]
              args:
              - |
                wg-quick up wg0
                KUBE_GATEWAY=$(/sbin/ip route | awk '/default/ { print $3 }')
                ip route add 172.16.42.0/24 via $KUBE_GATEWAY
                ip route add 10.42.0.0/16 via $KUBE_GATEWAY
                sleep infinity

