apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
  patches:
  - target:
      kind: Deployment
      name: source-controller
      namespace: flux-system
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: anything
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    memory: 3Gi

  # truecharts repo is huge
  - target:
      kind: Deployment
      name: source-controller
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --helm-index-max-size=102428800

  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=10
