apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 60m
  chart:
    spec:
      chart: immich
      version: 0.10.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  rollback:
    cleanupOnFail: true
  values:
    # https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
    immich:
      persistence:
        library:
          existingClaim: immich-data

    controllers:
      main:
        containers:
          main:
            env:
              TZ: Europe/Paris
              PGUSER: app
              PGDATABASE: app
              PGHOST: immich-postgresql-rw
              PGSSLKEY: /dbcert/tls.key
              PGSSLCERT: /dbcert/tls.crt
              PGSSLROOTCERT: /dbcert/ca.crt
              PGSSLMODE: verify-full
#              DB_HOSTNAME: immich-postgresql-rw
#              DB_DATABASE_NAME: app
#              DB_USERNAME: app
#              DB_PASSWORD: ""
              REDIS_HOSTNAME: immich-valkey
              REDIS_USERNAME: app
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-valkey
                    key: app


    server:
      persistence:
        dbcert:
          enabled: true
          type: secret
          name: immich-postgresql-app-tls
          mountPath: /dbcert
          readOnly: true

      ingress:
        main:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
            kubernetes.io/tls-acme: "true"
          hosts:
            - host: immich.${BCL_GLOBAL_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: tls-immich
              hosts:
                - immich.${BCL_GLOBAL_DOMAIN}

    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          storageClass: longhorn-single-local-replica
          accessMode: ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: immich
spec:
  storageClassName: immich-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-data
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle: immich-data


