{{/*
AUTO-GENERATED by the build tool (see generate/) from resources.yaml. Do not edit manually.
*/}}

{{- define "base-resources.render" }}
  {{- $rootContext := .rootContext }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "configMaps" "apiVersion" "v1" "kind" "ConfigMap" "contentIsSpec" false "stringifyFields" (list "data")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "secrets" "apiVersion" "v1" "kind" "Secret" "contentIsSpec" false) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "horizontalPodAutoscalers" "apiVersion" "autoscaling/v2" "kind" "HorizontalPodAutoscaler" "required" (list "scaleTargetRef" "maxReplicas")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "services" "apiVersion" "v1" "kind" "Service") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "persistentVolumes" "apiVersion" "v1" "kind" "PersistentVolume") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "persistentVolumeClaims" "apiVersion" "v1" "kind" "PersistentVolumeClaim") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "namespaces" "apiVersion" "v1" "kind" "Namespace") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "deployments" "apiVersion" "apps/v1" "kind" "Deployment" "required" (list "selector" "template")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "statefulSets" "apiVersion" "apps/v1" "kind" "StatefulSet" "required" (list "selector" "template")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "daemonSets" "apiVersion" "apps/v1" "kind" "DaemonSet" "required" (list "selector" "template")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "cronJobs" "apiVersion" "batch/v1" "kind" "CronJob" "required" (list "schedule" "jobTemplate")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "jobs" "apiVersion" "batch/v1" "kind" "Job" "required" (list "template")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "serviceAccounts" "apiVersion" "v1" "kind" "ServiceAccount" "contentIsSpec" false) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "roles" "apiVersion" "rbac.authorization.k8s.io/v1" "kind" "Role" "contentIsSpec" false) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "roleBindings" "apiVersion" "rbac.authorization.k8s.io/v1" "kind" "RoleBinding" "contentIsSpec" false "required" (list "roleRef")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "clusterRoles" "apiVersion" "rbac.authorization.k8s.io/v1" "kind" "ClusterRole" "contentIsSpec" false) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "clusterRoleBindings" "apiVersion" "rbac.authorization.k8s.io/v1" "kind" "ClusterRoleBinding" "contentIsSpec" false "required" (list "roleRef")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "podDisruptionBudgets" "apiVersion" "policy/v1" "kind" "PodDisruptionBudget") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "ingresses" "apiVersion" "networking.k8s.io/v1" "kind" "Ingress") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "networkPolicies" "apiVersion" "networking.k8s.io/v1" "kind" "NetworkPolicy") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "gateways" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "Gateway" "required" (list "gatewayClassName" "listeners")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "gatewayClasses" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "GatewayClass" "required" (list "controllerName")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "httpRoutes" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "HTTPRoute") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "grpcRoutes" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "GRPCRoute") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "referenceGrants" "apiVersion" "gateway.networking.k8s.io/v1beta1" "kind" "ReferenceGrant" "required" (list "from" "to")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "tcpRoutes" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "TCPRoute" "required" (list "rules")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "tlsRoutes" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "TLSRoute" "required" (list "hostnames" "rules")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "udpRoutes" "apiVersion" "gateway.networking.k8s.io/v1" "kind" "UDPRoute" "required" (list "rules")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "storageClasses" "apiVersion" "storage.k8s.io/v1" "kind" "StorageClass" "contentIsSpec" false "required" (list "provisioner")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "volumeSnapshotClasses" "apiVersion" "snapshot.storage.k8s.io/v1" "kind" "VolumeSnapshotClass" "contentIsSpec" false "required" (list "deletionPolicy" "driver")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "sealedSecrets" "apiVersion" "bitnami.com/v1alpha1" "kind" "SealedSecret" "required" (list "encryptedData")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "clusterPolicies" "apiVersion" "kyverno.io/v1" "kind" "ClusterPolicy") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "recurringJobs" "apiVersion" "longhorn.io/v1beta2" "kind" "RecurringJob") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "settings" "apiVersion" "longhorn.io/v1beta2" "kind" "Setting" "contentIsSpec" false "required" (list "value")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "routes" "apiVersion" "route.openshift.io/v1" "kind" "Route" "required" (list "to")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "helmReleases" "apiVersion" "helm.toolkit.fluxcd.io/v2" "kind" "HelmRelease" "required" (list "interval")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "kustomizations" "apiVersion" "kustomize.toolkit.fluxcd.io/v1" "kind" "Kustomization" "required" (list "interval" "prune" "sourceRef")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "gitRepositories" "apiVersion" "source.toolkit.fluxcd.io/v1" "kind" "GitRepository" "required" (list "interval" "url")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "helmRepositories" "apiVersion" "source.toolkit.fluxcd.io/v1" "kind" "HelmRepository" "required" (list "url")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "ociRepositories" "apiVersion" "source.toolkit.fluxcd.io/v1" "kind" "OCIRepository" "required" (list "interval" "url")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "imageRepositories" "apiVersion" "image.toolkit.fluxcd.io/v1" "kind" "ImageRepository" "required" (list "image" "interval")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "imagePolicies" "apiVersion" "image.toolkit.fluxcd.io/v1" "kind" "ImagePolicy" "required" (list "imageRepositoryRef" "policy")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "certificates" "apiVersion" "cert-manager.io/v1" "kind" "Certificate" "required" (list "issuerRef" "secretName")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "certificateRequests" "apiVersion" "cert-manager.io/v1" "kind" "CertificateRequest" "required" (list "issuerRef" "request")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "issuers" "apiVersion" "cert-manager.io/v1" "kind" "Issuer") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "clusterIssuers" "apiVersion" "cert-manager.io/v1" "kind" "ClusterIssuer") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "orders" "apiVersion" "acme.cert-manager.io/v1" "kind" "Order" "required" (list "issuerRef" "request")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "challenges" "apiVersion" "acme.cert-manager.io/v1" "kind" "Challenge" "required" (list "authorizationURL" "dnsName" "issuerRef" "key" "solver" "token" "type" "url")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "clusters" "apiVersion" "postgresql.cnpg.io/v1" "kind" "Cluster" "required" (list "instances")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "scheduledBackups" "apiVersion" "postgresql.cnpg.io/v1" "kind" "ScheduledBackup" "required" (list "cluster" "schedule")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "secretStores" "apiVersion" "external-secrets.io/v1" "kind" "SecretStore" "required" (list "provider")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "alerts" "apiVersion" "notification.toolkit.fluxcd.io/v1beta3" "kind" "Alert" "required" (list "eventSources" "providerRef")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "receivers" "apiVersion" "notification.toolkit.fluxcd.io/v1" "kind" "Receiver" "required" (list "resources" "type")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "providers" "apiVersion" "notification.toolkit.fluxcd.io/v1beta3" "kind" "Provider" "required" (list "type")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "stringSecrets" "apiVersion" "secretgenerator.mittwald.de/v1alpha1" "kind" "StringSecret" "required" (list "fields")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "ingressRouteTCPs" "apiVersion" "traefik.io/v1alpha1" "kind" "IngressRouteTCP" "required" (list "routes")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "middlewares" "apiVersion" "traefik.io/v1alpha1" "kind" "Middleware") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "networkAttachmentDefinitions" "apiVersion" "k8s.cni.cncf.io/v1" "kind" "NetworkAttachmentDefinition") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "serviceMonitors" "apiVersion" "monitoring.coreos.com/v1" "kind" "ServiceMonitor" "required" (list "endpoints" "selector")) }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "validatingPolicies" "apiVersion" "policies.kyverno.io/v1" "kind" "ValidatingPolicy") }}
  {{- include "base-resources.generic.renderAll" (dict "rootContext" $rootContext "name" "verticalPodAutoscalers" "apiVersion" "autoscaling.k8s.io/v1" "kind" "VerticalPodAutoscaler" "required" (list "targetRef")) }}
{{- end }}
