apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-postgresql
  namespace: authelia
spec:
  instances: 2

  storage:
    storageClass: longhorn-single-local-replica
    size: 4Gi

  bootstrap:
    recovery:
      source: origin
  externalClusters:
    - name: origin
      barmanObjectStore:
        endpointURL: https://authelia-postgresql-backup.authelia.svc.cluster.local
        destinationPath: s3://authelia-postgresql-backup
        serverName: authelia-postgresql
        endpointCA:
          name: authelia-postgresql-backup
          key: public.crt
        s3Credentials:
          accessKeyId:
            name: authelia-postgresql-backup
            key: MINIO_ROOT_USER
          secretAccessKey:
            name: authelia-postgresql-backup
            key: MINIO_ROOT_PASSWORD
        wal:
          maxParallel: 8

#  backup:
#    retentionPolicy: "60d"
#    barmanObjectStore:
#      destinationPath: s3://authelia-postgresql-backup
#      endpointURL: https://authelia-postgresql-backup.authelia.svc.cluster.local
#      endpointCA:
#        name: authelia-postgresql-backup
#        key: public.crt
#      s3Credentials:
#        accessKeyId:
#          name: authelia-postgresql-backup
#          key: MINIO_ROOT_USER
#        secretAccessKey:
#          name: authelia-postgresql-backup
#          key: MINIO_ROOT_PASSWORD
#      wal:
#        compression: gzip
#      data:
#        compression: gzip
#        jobs: 2

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authelia-postgresql
  namespace: authelia
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: authelia-postgresql