apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: authelia
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kube-lldap
  target:
    name: authelia-lldap-cert
  data:
    - secretKey: lldap.crt
      remoteRef:
        key: lldap-internal
        property: tls.crt

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kube-lldap
spec:
  provider:
    kubernetes:
      remoteNamespace: lldap
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: lldap
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets