apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: authelia-secret
  namespace: authelia
spec:
  provider:
    kubernetes:
      remoteNamespace: authelia
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: external-secrets
  namespace: authelia

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-secrets-reader
  namespace: authelia
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: authelia
roleRef:
  kind: Role
  name: external-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-reader
  namespace: authelia
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create


