apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: authelia
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: authelia
  rollback:
    cleanupOnFail: true
  values:
    # https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
    ingress:
      enabled: true
      certManager: true
      tls:
        enabled: true

    #################
    pod:
      kind: Deployment
      env:
        - name: TZ
          value: Europe/Paris

    secret:
      existingSecret: authelia
      additionalSecrets:
        authelia-postgresql-app: {}
        authelia-valkey: {}
        authelia-oidc: {}

    certificates:
      existingSecret: authelia-certificates

    configMap:
      theme: dark

      telemetry:
        metrics:
          enabled: true
      storage:
        postgres:
          enabled: true
          address: tcp://authelia-postgresql-rw
          database: app
          username: app
          password:
            secret_name: authelia-postgresql-app
            value: password
            path: password
      notifier:
        # filesystem:
        #   enabled: true
        disable_startup_check: false # in case of emergency
        smtp:
          enabled: true
          address: submissions://mail.awired.net:465
          sender: 'Awired Authelia <authelia@awired.net>'
#          identifier: authelia.awired.net
          username: authelia@awired.net
          password: {}
#          tls:
#            server_name: 'mail.awired.net'

          
      authentication_backend:
        ldap:
          enabled: true
          implementation: lldap
          address: ldaps://lldap.lldap.svc.cluster.local:6360
          base_dn: dc=awired,dc=net
          user: 'UID=authelia,OU=people,DC=awired,DC=net'
          password: {}
          tls:
            skip_verify: false
            minimum_version: TLS1.2

      session:
        expiration: 16 hours # sessions expires every day
        inactivity: 8 hours # destroy sessions if nothing is done
        remember_me: -1      # always apply the same behavior
        redis:
          enabled: true
          host: authelia-valkey
          password:
            secret_name: authelia-valkey
            value: authelia
            path: authelia
        cookies:
          - domain: awired.net
            subdomain: authelia

      password_policy:
        zxcvbn:
          enabled: true
          min_score: 4

      totp:
        issuer: Awired Authelia
      webauthn:
        display_name: Awired Authelia

      access_control:
        default_policy: deny
        rules:
          - domain:
#              - authelia.awired.net
#              - ssh-gitea.awired.net
              - gitea.awired.net
              - home.awired.net
              - lldap.awired.net
              - longhorn.awired.net
              - mail.awired.net
              - grafana.awired.net
              - alertmanager.awired.net
              - prometheus.awired.net
              - fluxwebhook.awired.net
              - rutorrent.awired.net
            policy: two_factor
            subject:
              - [ 'group:role_admin' ]
          - domain:
              - jellyfin.awired.net
            policy: two_factor
            subject:
              - [ 'group:app_jellyfin' ]
          - domain:
              - gitea.awired.net
            policy: two_factor
            subject:
              - [ 'group:app_gitea' ]
          - domain:
              - pushprox.awired.net
            policy: one_factor
            subject:
              - [ 'group:app_pushprox' ]
          - domain:
              - whoami.awired.net
            policy: one_factor


# Allow service accounts to log to mailu with single factor. But useless because:
# - SA do not log in to UI
# - Accounts are created on the fly by proxy_auth
# - submissions are not authenticated against proxy_auth
#          - domain:
#              - mail.awired.net
#            policy: one_factor
#            subject:
#              - [ 'group:role_service', 'group:app_mailu' ]

      identity_providers:
        oidc:
          enabled: true
          jwks:
            - key_id: ''
              algorithm: 'RS256'
              use: 'sig'
              key:
                path: '/certificates/identity_providers.oidc.jwks_rsa.key'
              certificate_chain:
                path: '/certificates/identity_providers.oidc.jwks_rsa.crt'
          claims_policies:
            grafana:
              id_token: [ 'email', 'name', 'groups', 'preferred_username' ]
          ## See: https://www.authelia.com/c/oidc
          # generate a client_id
          # docker run --rm authelia/authelia:latest authelia crypto rand --length 72 --charset rfc3986
          # generate a client_secret
          # docker run --rm authelia/authelia:latest authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
          clients:
              # gitea admin auth add-oauth --provider=openidConnect --name=authelia --key=gitea --secret=insecure_secret --auto-discover-url=https://authelia.awired.net/.well-known/openid-configuration --scopes='openid email profile'
            - client_id: 'gitea'
              client_name: 'Gitea'
              client_secret:
                path: '/secrets/authelia-oidc/oidc.client.gitea.value'
              public: false
              authorization_policy: 'two_factor'
              require_pkce: false
              pkce_challenge_method: ''
              pre_configured_consent_duration: 1 year
              redirect_uris:
                - 'https://gitea.awired.net/user/oauth2/authelia/callback'
              scopes:
                - 'openid'
                - 'email'
                - 'profile'
              response_types:
                - 'code'
              grant_types:
                - 'authorization_code'
              access_token_signed_response_alg: 'none'
              userinfo_signed_response_alg: 'none'
              token_endpoint_auth_method: 'client_secret_basic'

            - client_id: 'grafana'
              client_name: 'Grafana'
              client_secret:
                path: '/secrets/authelia-oidc/oidc.client.grafana.value'
              claims_policy: 'grafana'
              public: false
              authorization_policy: 'two_factor'
              require_pkce: true
              pkce_challenge_method: 'S256'
              pre_configured_consent_duration: 1 year
              redirect_uris:
                - 'https://grafana.awired.net/login/generic_oauth'
              scopes:
                - 'openid'
                - 'profile'
                - 'groups'
                - 'email'
              response_types:
                - 'code'
              grant_types:
                - 'authorization_code'
              access_token_signed_response_alg: 'none'
              userinfo_signed_response_alg: 'none'
              token_endpoint_auth_method: 'client_secret_basic'

            - client_id: 'jellyfin'
              client_name: 'Jellyfin'
              client_secret:
                path: '/secrets/authelia-oidc/oidc.client.jellyfin.value'
              public: false
              authorization_policy: 'two_factor'
              require_pkce: true
              pkce_challenge_method: 'S256'
              pre_configured_consent_duration: 1 year
              redirect_uris:
                - 'https://jellyfin.awired.net/sso/OID/redirect/authelia'
              scopes:
                - 'openid'
                - 'profile'
                - 'groups'
              response_types:
                - 'code'
              grant_types:
                - 'authorization_code'
              access_token_signed_response_alg: 'none'
              userinfo_signed_response_alg: 'none'
              token_endpoint_auth_method: 'client_secret_post'
