# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu-pv
  namespace: mailu
spec:
  interval: 60m
  chart:
    spec:
      chart: base-template
      version: 1.250501.709-Heffe9b6
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: bcl
  rollback:
    cleanupOnFail: true
  values:
    resources:
      persistentVolumes:
        admin:
          size: 20Gi
          storageClassName: mailu-admin
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-admin

        dovecot:
          size: 20Gi
          storageClassName: mailu-dovecot
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-dovecot

        postfix:
          size: 20Gi
          storageClassName: mailu-postfix
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-postfix

        rspamd:
          storageClassName: mailu-rspamd
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-rspamd

        clamav:
          size: 20Gi
          storageClassName: mailu-clamav
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-clamav

        webmail:
          size: 20Gi
          storageClassName: mailu-webmail
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-webmail

        mysql:
          size: 20Gi
          storageClassName: mailu-mysql
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-mysql

        redis:
          size: 20Gi
          storageClassName: mailu-redis
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-redis

        webdav:
          size: 20Gi
          storageClassName: mailu-webdav
          csi:
            driver: driver.longhorn.io
            volumeHandle: mailu-webdav
