ssh_host_ed25519_key: ENC[AES256_GCM,data:YPpDlIC0MDstPmIDxR/uPdQ87KvRVM/AHNnIc3YQcAVbrqLnPXTTCigTr3urIk5eO27VzFiFKSDvQwoKXVmTjE+1aRyT+3uZtlKj1G1w9SVcK4UuS6TStzYFKaE4Om4ZHCGkTXmzuQAqR+yNYq8WraJQ4RrkKvQkJGieGbyFitCPywLR4YFQSS0BoULy7bDTt1d2pNJ2D/PtHHONb+pyU7X1Q+5Cj12s2iYzQsI2pnv2ozgvEWpkuFwjeYeR3YEXUoYxOXe6GuoUkkKxy/5N+nISgIUx2QMwRezTert9MvL47UyuKHRKbUnqqDEI0NQK/0Ig75IX4aUGkvMKIDSq5jWh/zBzJ1eOx+WFodmKZHPrgNi0UBlB301Ok+Yl7nmbN8aTKr1YtynbsxKm3EFjZJo2bhURxpwMvToKKfbWDxyUACG5K2D7+cMROJV4R3rP9Y0MjiYC/Ui3WX383GPcx4ngu1Ay3zixknWxMrR6JVMBpDZF0a8Hy/M2r52LeZmUs5KDlhABsUiDc2bsAhEG,iv:mmPqjs/N3CvBznFm3xPCGtw7efvj2L4fMiwywZtaUBo=,tag:Mk10rCZf8FIwjfil8DiNHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gzscll8gj2sefp37v50yt7ae8pjs28trf4aupekfz7zqvwn4xgqswtgg2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK2dQbzIyVk9MbThURC9U
            RHRmUmY5RmdzdUVUQTEzelB2M2ZKZ1p0NVNvCjNDYjRydllDV1hKZlJyK2xFTXJh
            S2hJMnZ1Zjh2T1pvOTNaOG9ZbzlrYU0KLS0tIHVnM2xCSE5wM2NQT3pLdlVjdFNR
            Y0RVc1Y2cVphS0lkZ0NMOHBkd21UWEEK0zGdAmPsl1mBcKpl3cgOmz2778TrfMZS
            vyGaIBqB4jV0nfPNhcu4Ync69FW42S0UtkZx/Rdw51KyS0ueG26Zkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age146vcg407p7ayhzag4d9pmze47du0lakwjtvxp5gyjnjfa62lp9ssdjnd83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRml6VjJTM0pSSi93SzFP
            bmR3VGNCWmRpSHlnYkFVZEpjZVk4WkZZZXpjCmIvdU5GVXJhSFZ4RDNUZllWRkNJ
            WHFFcXBhNFdPUW1nVC91aDlraEY5ZVUKLS0tIEREaTl5aG0yR0xXckNydjNtVXkz
            dEw0WGZYbVhacHNqM1VKSmR6VlFLalUKn1Xf8lz0TukwTpY6YZCdUlVgLQSxaxiH
            S2sy32U4NUVxrMYUCgqzGR8qATqlwCdaWCwnTMuRQSo9EcP5p2xuKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T10:31:58Z"
    mac: ENC[AES256_GCM,data:pQIecAmp/8x2HVpz3p85tQqydm5OfKQIMJmcEjb1hDDOq0msjPu5Kl6cLXNEIX9+Yw1n7EwLhMzfSAkT9v3vFlKIbW37rwomkr3nduQp3D1rXb/IM6Y3dbNSS3yg1NxMgrhJfB/ZOkH/KV367osg9KMFCvy7LlHNe71vDs4DJ7I=,iv:Kh2AdkbIfhjeOex9gNjXsO8IQtgZyRdB8PueESzpLpI=,tag:tgZUKPmd/RSQviyJmbPp+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
