users.kwiskas.password: ENC[AES256_GCM,data:sMzmzfVH7YjIiqpr9WmAGg+MfpPDbD/5vrzNoKrCP6V/p2z3bgx2mRB9lJ6uFlOwQmMV7F2Hz9ralEKS8E8tCI7oh2E98JnG6w==,iv:YuOXbWttbjzdSaOIiqhx/IgvFplSckjXY/29ctSe1KM=,tag:iqYPDOmsvRDQflVaZf8LlA==,type:str]
ssh_host_ed25519_key: ENC[AES256_GCM,data:sS1UikUdC86q10F4kvbta1/LF8W5WfevAapgVpBQUoc/11OqD62H/9Fg/yga+CmeaEx5oi/gqcnfVux9mNHIa2CLezVbC5HqaTXXcw7eSJW/c+35EQd9rZ5K3UUbDSWnPO1FE06CRjOgYzYUJORXb3bLxo5l6qdbJ3kQ3cZtv7MchRjSPQW4STjfb0r4VOqRUifgtqqymXMucE7RzsThZ7htpL0SZCSOn024u91VEH0El94RjrL0A+f0fhFr2EqBrrmcEGSaAylZZ9hFOklAuWre6yVLtXMextbmZcTZfUKFDCD7/IDzZdlN2eQdhNo89R5RAWOmqJ+kUOEwrfssRR3OuhpDGJZ9ksdfGiDfXi7HOuYV9AzbRb6nleqDSrmKyRuipRhIRsMeiFcbEz1IdIOeDDrQQk4WHZa4AgtvQuxz9mAu9J5ZJ01I3vPMGRZ1p5F40Gs4VpjvyEcJX3x22gTREbmJAn3B4suNlqTImUzDi2OBAN5GnhI902bP0aAIllhkh29N4z5eES0/g/Y0,iv:TznW0eslUs8qH6dXpHhVlgESIXmvzmWLNO5k7INxHbI=,tag:zl4iYNgqItryOkqMXilCCw==,type:str]
syncthing.hideki1.cert: ENC[AES256_GCM,data:JVAwRljZwI8iiqluSZcnok2hGSw/Pr5mXRh1tppOSCxAlnKca6OR6OlNsY+Bo2ErSpKUYJe7I640IpZ1dJ2tsSrWw1zXaHZzR6NGdCHGpGnk42Ehk0uv/dpiygEXog3i26njYasfUbEzQzF8NZq0cEhB74b5OFNBSbYUNNPjRMhImaJ4rN3EoSyBz7vvpAql/ys3JoKOyvCkz+L8NsmxX6IVJ53VUNR1sYLFR5LR1SnbNMdWvptSFQOkDzxkFddp19hNXkL88X+MzZXziaUp3u7KBcmqnyFMJeAtzGX8eBWDGmeRorEljN6G32H1p+ir7C1rzLHTMmsqDZHorRuqPhUnxr3FLjHnLx+Cj8R51VHzy+ohsTAX2x2zko9ZLggscxVAIwsfy9gyN0fT4sn0pbz/+9SJLXYbNdNi3owFvkcLKYhy0LvDFst8CImk2xQgjfcPl+oi4ThBa/F8DL2kpFpLAnbV9FXeiGMLaPtNRi6ivvNrZDxHIQyJGOasLVXAxZkr4TbC/662JzDp4n+KH5NCWFM6fzRSgbj7QfnSCspCj6dmKRXK+sexch8UGuiiFhlE/cZcNrSPQvwuWPawR1nJazp+v5UFcTUr5kUVvmCjWR711bhfVDhsr5vXTc2XaUfksVcfP25sVPCjrmX+tpHvYJg7v5hvkyC0dK+lDufZsmtpt0wq/RwQopErov908SKpJR54a3zGc1GuL8B5PDoy4CrAvUQPWIPDOEw6/mjAdxOCPeLtKU24yJDWC+bpuh85jwrr58KLUsuhggvrrgdtSImUT7bejMWIL30UyVxK/SqZt94gsnOlOfJxtLwFy6uYQWh1eCKd+t45KTa+1qSu0Y02lV8O9KfnUKDg3wkVv4MfhmjFwp/5HOJrTU86ZpDTIdSxRnoXOsa3Q1hO2gv0q+WhZ56eFTggF+NVzZmePRP9ScTuesLtXlo0gHUU2OWyQNTNCquqt8EYB5ID+0mAGPn/Wy/3esmjVe5GbCdQTIP7IGyWkBqf20iHl66WWVsPfH7w6xyD0yYzy5N/G1bdbJ8q,iv:d0fmhl2GUq23IRUEYWUwHxLVR3dmwRx5JAsXBgxL19M=,tag:KPoTJQ66djFb2DBtucJpKw==,type:str]
syncthing.hideki1.key: ENC[AES256_GCM,data:JUea8P5M4gT2EqAJ469J3+GpvMnXFjIQqStO3kbTojse2Uq37mphWg5s2E9sfAKYhKjAPOj37aWatK7TiMVCWk2yJ11OiR//Ero6c31FGo4nfItF52yGuMLjuhTSW6pAr0Yiu2ww/KzRNo9zYNocYS/coSf0fgyYDT55AG4olnbbtUvA+oRh0uKGQTjYR5N6o7kTlhFzPPA7Nrfr0bJbQXgI924AAaRrGdHuD9IMM+nqlr2esmsyml5XuTvuWnbH5MgrzpxX71O84nunlojiAt5wkF6ws+Wi6FDxshvzE/U/LPoypebjyIOfoaYGhi9qJDdpeIGPDNfcerPPtuXFtKeW5JsEz2HONdLYA+y6a2iftrjd8rZftALtx30HcT5M,iv:Lzn5CDKUG9QWzrULkQK/Syb0PsB7lydvwDTaekjJ76g=,tag:OpoEj59vx3oaRAr2fRQiVA==,type:str]
syncthing.hideki2.cert: ""
syncthing.hideki2.key: ""
syncthing.hideki3.cert: ""
syncthing.hideki3.key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gzscll8gj2sefp37v50yt7ae8pjs28trf4aupekfz7zqvwn4xgqswtgg2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Mi85YjRXSHE3VE5iVXR2
            Nm9uZkh1TFE0VXlLNVF6RjlsSFF0YmxFU21FCktOWDRmSXp3cDFsbEZKSXFxS1Jq
            MmlHc2JIbEJIbHJJeEx3Rlh5em5hTmsKLS0tIEZjMCt2TTNDcVF4VnhhRlU0bTBH
            ZUVCOWxFN0lnaWgvZEdxTkJEYnREVTQKJtihf9G0GRXOEv1Q892NV1Md0i/at2LW
            iaw+arkm0ic3Jgme51/YgmV31tlyMB3BVNn6rwe5pkdNhXeE61xZ2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k4fkp0sdmuw4ewsc00vj5h2rptk0r02c8npszs02xs35d5e3y9gsc9tk2m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocHBqUFRjVzdpSmhUU1kr
            Z2ZpN1lLektzOEIwcHJKZElTMERYZUkwMFFzCkllSzJBdkd2cmErTUlXOVNETHkv
            Z0VIeEk5eVBVaHVHQWljZzF0WklqbjAKLS0tIE96R1A2Kzd0aTNLcVRvQjdaUkd6
            cTNZaDdQaFdMZkxiRmt1WlZ2SlFIRkkK84OXqr3jLyb968hzc4VO8iKzRrQYoa91
            lnK5c/93t4qxE+eovfJFjKCObsXB6bRJ2Wb4O7wxxoQBnBAAkStDCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T21:48:46Z"
    mac: ENC[AES256_GCM,data:oyTw4DdQ4LyjOn7lYQOWseABqXyCzfGupkYbkeyAuN66jyOoeNaEh2OO8HIpec9UnyAEizp5I+PU33wVInzLefzKnYML9n4CloIKXu16KcC5G7Ql5AmViblZcCBrIDDjr5sfSjuj3W64XqaFRUlh1O6CjUBYxt4W5zxQBGwUW+E=,iv:L/r3h2wW2NW54JMlv0FgQGlitIO3yfA0wWlXyqGlC6c=,tag:i4Xv9EOLgUnjp6R9XxY2xw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
