ssh_host_ed25519_key: ENC[AES256_GCM,data:3Za2RDASCHBfoAokx9rOVMzaUw//5LrHI8PVgIag+HXPjLQWhfOwjgVcK3qceXdJ/Ky6jUyaXEXV9S4z34FzZGmIAlYklPtAuxHdaJzcZh6LaG94acXrs1klJZy59bfmZsAka3BuvoEnkCedy/AclQjT6qAcugT7I91bXKn1CLfVykQTVdlFrCHftIYt7JMULA0/Z8Zq/aujisVhAnkoiBAwBjXZsOi1zlxdd+Vj7lWKfClZhy/roem0UDsU/uIFSYi4+FTKhvzcu2YUcJ35vkqj46rewzzb+TZufDiNc5q82KAzLvZcgz0uA88i878oBoG3B5aoaruxNWgfYX57SU/C2I3bnveRm+mHZoiR/aiZY+oRR/QOYjZsk2wwAkJjShmTMZfImHZyj4jWCSclQsICKQbot3JyMmooMkLDdSI3UFGRYnIGHKvcsu1Hszsw6z9iX59hIg8Ioh8+C8UerxHtAz+7MuJdhpes3WQWBMocu6VsHhadE9GT6Fs0/IEoembC2Nk2pgo/ldEeTf5Z,iv:zDhsfU2QMeuTWfXTYhZ20qK7Ga9hgEU8BqFLTlC5N/I=,tag:hmmBXEj0G7xDMSnC6ETaSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gzscll8gj2sefp37v50yt7ae8pjs28trf4aupekfz7zqvwn4xgqswtgg2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN3NFK2UxYUx2S0hkbTdD
            RUh3dE0rNGoyQ1Q4bytYbnpPNVRCTzdUWlZrCldRekpFWGV5RE82S0g0NzBqR3A0
            Zm1jMlI0dS9ScTRSakZiVlI2SERiUm8KLS0tIGpiREgrdVRxTHE1cVF4d2Y5cHlW
            V1FvYjNpa21KMmZVZGlta1VKak5WQnMKdTJPX2pIzrKbvxXGc68szAszSBiEyPAm
            H+r2wohkmFUVDXWEHGXED5sKSvHL4+0msoSSjrDqwNEU4mIMnwdSbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14x2wgdzzcgsm9a9f7h77exfjda060kahhaqn6dftsfq6l47lk35qx5qftd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL3Zaak9xVnBKNnF6NXp4
            TUJkaEJnVUlsQ25tNFNPc1dOdDVjcEh2YndBCnpsa3I3TGwvQi96ckFMVC9JRWc0
            REpJMWJYN0dNL2hERmF3dEt1RHhESzgKLS0tIGJ1OUFaS1RiV2laR3NXcVhJakNZ
            OFM5UVJSN1EvMlZXUDlhRDFrdUlDNWMKAKWU0fF59dLp9mqpMWr7hFiIs+DLxWu0
            dqCpx/zpnhhwkYXoEx9i8yb2QUqWmzES+HnFuKHsSEjdcCIQ+p6Y2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T10:33:11Z"
    mac: ENC[AES256_GCM,data:EPl5krD1L4saC2kleJqAN8/o5HPUrPwQ0F9Q+efqILATsetoKMsr3jc6/3Rf6Bb3gPZRJfphzfWapn7dK23r7kXKz3gPX4rsRaY+sHk+nygdqDlggGk9Q7aYmtVCulz0S8cRiRsbYxn5mm4dDVzOdQfs6ZrhqplcDY2dfR6tFZc=,iv:Czl2M9Rj/ZTgxEykoCxd2zuM7y/Dal9NImSb51RjITo=,tag:UQQEuqDqZhBKhYwqbuDhWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
