ssh_host_ed25519_key: ENC[AES256_GCM,data:g+AOhWz1R9f01WEoZkxQjcQgHgSI5/nXi+FQvwuxPtedl/bNLBZq2Atzy39WfaLfSLEVPEUbWOmiF4Uuz1aeCRU/DulYZU9bPYxmuGyUTyCAT6weOYO2jzELtX1NgGZdmiGmKs7/lcFIw1PElkGJuEL8/+lT2RZ/ntfKevHpdTFA6k2XM1nXlWt8kusLHjUhGU3OUv1gbXukdleZcedXhohXNRIaNKLTE8OX+d2WvfzJ9Vg0O0M8HLPHb+d2qjMKd8xMVEwcy79L/JcRo66cDsDrcy82fKViWIf8ErK+tGWshbxB4xrHEHN6gIOZ2aht76R1IbPw6qL7puWMRTptO5B420LSYgdC+mJP0ZPSQl6Xc5xuwAn7f7HAWtlyms8UMfHlHzxWa3K2d0IyyIJ3BR7KMB8SN9b7mas/BmKFUEmKm3oEkldiSNaB6jx4YpezxTjx2bWwpzVtI7r/H/vnHgsL0ziFDUETb7U8LGG7PXykToLbUALM7T7LquhCCd2oeaK+9MHxeB6U1lCGAlxB,iv:qPqgPVCTFaU34ovuthralugSUitoKmnikhahdhMj1YY=,tag:WqqF36v+qP7avJAMJJe7mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gzscll8gj2sefp37v50yt7ae8pjs28trf4aupekfz7zqvwn4xgqswtgg2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdHp1R0JsN1RhcWFGT2Iv
            a3dBc3JBQWM3UFlTTW8xdmhDQ0hqK2ZzQm1JCnA0WTFuRGdXaERFOTJWeVRLWTI5
            Z2owcU4reHJtWFFqbDJaUnU5SXcrVEEKLS0tIEJxNFNHdFh6anZZTWpsZkVmNlNk
            dEIwTjlMOGFjSTc4UldJT1ZGOEFPZXMK9vUUF7DzbesnMRukpbxIwCuwrdNhPie1
            4UM5ZdwQRI/XPqaqF2aEdCQJ1V9DY8hcSpk7MEUVacChz//f3Z53+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kxdm2f2j2ups2cprcsa8k6029cqcnx5nqwn0yxp8pm89636zl9rshhx8te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOWFGRXVCRGxyVmw4VVF4
            U0dxVFdxcFh1Q2xFV1lWZXNXZkU1YjhxdUd3CjlJc0RMSnJXZXdMRW5YaEhjZTBJ
            dTcyS1krb3FleFliaGpDeHk4YXRzeDAKLS0tIDgwYVNSaHhPR0pZQ2hLak5lMUJn
            cEN4QWZ5M0NnMlpkUmFmK1A0bDk1dEUKAjTnVCMgAt9zA3hQMntc2cZTDJ0DzlVb
            34nCP4xQf4rd/djn7jH8sfYiYMRN3ZTAF1kH4+GPbswOtqAnGSR0mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T23:12:29Z"
    mac: ENC[AES256_GCM,data:Oq8hKFPGHztwwypHRwXYkdZt4r6LqBHPeVvXfTDeevfPaHUOwkwgSQEEcdO2vtgbAKaLL3oiBGjI+2kqpqQUXo31sEOgzZYIQmW0LabNn3xxd2rkmzuMXnmq8xtII1jpnnf+bzymCmOS+1f+cXdIIu7ChuYKvFKpp1zG0CPKIgw=,iv:n71SrNwZwb0yy/QgJIFjHD3zKS67KJJrcRiyt8GLvps=,tag:Km5CfjlAAWnlMssqxj1ALw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
