ssh_host_ed25519_key: ENC[AES256_GCM,data:AL2ddIPlc6X1eZytmPGsvbjvwIHrCmmVVp07MYFGHYmfyISWUB5SI3tSGNBxJoFu0CoR3jRgwTXDXUlMq0LwNqrQ5NCtTqXkh4Wo2TW8zPmpRecEeiqkwrp/BT2jrwgI5im/ycmCDC7UJt/hdO3ndtwdE7dyc+J++pQOSCiw/GGZSxmie43DPHvofUaYw8MmB2j+4TdmbHgMJ6w92mudQbdhRQKNLkWM27f294qyHRKWP7JVcX7R43drgc9Q3YIkTryx959YzTcU74MkNGrDVPpAUkRZobD74K2zYDVG2Dvtzi8LvtBchN4jtJWn8aR6spas/GgmaX2T55Dav/lc8yXhxOWd8nmLZaGr0Fw35QbnaOeo+MQLi2itDkOfVC9eu2MsMf2iARv2XImGMN0IdwjkQ/XsrPGYv1G4J/6E0H8PnS6Vpp7aTU0/M+GL2UHZxJh76ekCawvJadfY6twdTeL+YfmI2DyiHME6Q77mWTCamEHSNgy+YnPxNZJgn1zGCUa3phHReBb+Tzt7+DAy,iv:7yarb1fQ6B1BeSr0GjV+9t4dgUwNrA0fcpwIThOMFJo=,tag:NkWuuMUWJECxVjG00iTqCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gzscll8gj2sefp37v50yt7ae8pjs28trf4aupekfz7zqvwn4xgqswtgg2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVEFWaG1KdmJaaG43UUdy
            dkFhaG5BVXRnN1ZJUDBkSElJU1h3ektURVVFCkpsc3ZLbUZkWjVkRjN4dGwrWnY5
            Y09PVGEzeWpkNWwzazdkMXNkREI4R1UKLS0tIDFlTGZrQzFuMW9lZVk5Ui9IdHdE
            UThaenZWN1J0VW53Wll1d1o2MEJSemsK3tVpsw4ty2ydEANq5E+LifVfWvNC/lLm
            /vSPlKjGS51ip0364Q/dZ5l7efh8bUVXGUWkWZ5K1jU3QFKW4Ng68A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10rlc34utel3slclkqzda0ccq4kgpzwpjemdfrc46452nnkw8l3hq9ss94y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaW13ZFJmMURrQTFmUGlR
            anM2Q0VJbUF3cTdyV0FiczZrMTFJUXlUdHljCjlyYm9FYlJJSithaXJLT1lreDVl
            VFg0N0hGa1pTQW5xZ0l1NUxLUTZUOVkKLS0tIHExMFBSamthTXJrMVNVbDBUT0Nt
            ZmxydU94VFhpV1RlcVNLeGVabUIzWGsKtIO4i1FpVKMQ/0fb/D32AGvIyFmYQl6K
            ZbsE6oNMdXng5BAvHqk6rKF2HfLFfu9ZfjoVqT4Uoetjx+ZM8tRhdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-15T14:08:18Z"
    mac: ENC[AES256_GCM,data:qHIWVQD/4JBRe05vLJ8j/wnxmvoYiiyww5Nqinbn2YqvOqbGZhkbUobsThYhY+KBOoOZTcxsrwqOQV6GqxsS9Hqpi0/qyNrimj02KRs2DElkJ8SqF91ff39PlXVuIvm4FGJx0uf6FklAGYhqmv2qVTTqgadm+O/YYDyrsffVr3k=,iv:NG56mbXL/wn+OTcHy0PNHUJxt/fxtZzOVgNiqZmmexE=,tag:QXuw5VipiEEc0283so9XjQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
