apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: forgejo
      version: 17.0.0
      sourceRef:
        kind: HelmRepository
        name: forgejo
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    replicaCount: 2
    image:
      rootless: true
      pullPolicy: IfNotPresent
    extraVolumes:
      - name: forgejo-postgresql-app-tls
        secret:
          secretName: forgejo-postgresql-app-tls
    extraContainerVolumeMounts:
      - name: forgejo-postgresql-app-tls
        mountPath: /dbcert
        readOnly: true
    postgresql:
      enabled: false

    gitea:
      admin:
        existingSecret: forgejo-admin
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true


      config:
        APP_NAME: "${BCL_GLOBAL_NAME} forgejo"
        database:
          DB_TYPE: postgres
          HOST: forgejo-postgresql-rw
          NAME: app
          USER: app
          SSL_MODE: require
        server:
          ROOT_URL: "https://forgejo.${BCL_GLOBAL_DOMAIN}"
        actions:
          ENABLED: true
        service:
          ENABLE_PASSKEY_AUTHENTICATION: false
          DISABLE_REGISTRATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
          ENABLE_NOTIFY_MAIL: true
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          DEFAULT_USER_VISIBILITY: private
        ui:
          DEFAULT_THEME: forgejo-dark
          ISSUE_PAGING_NUM: 100
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: true
          WHITELISTED_URIS: authelia.${BCL_GLOBAL_DOMAIN}
        mailer:
          ENABLED: true
          FROM: forgejo@${BCL_GLOBAL_DOMAIN}
          PROTOCOL: smtps
          SMTP_ADDR: mail.${BCL_GLOBAL_DOMAIN}
          SMTP_PORT: 465
          USER: forgejo@${BCL_GLOBAL_DOMAIN}
        attachment:
          MAX_SIZE: 2000
        webhook:
          ALLOWED_HOST_LIST: '*'
#    persistence:
#      enabled: true
#      create: true
#      accessModes:
#        - ReadWriteMany
#      volumeName: forgejo-shared-storage
    ingress:
      enabled: true
      hosts:
      - host: forgejo.${BCL_GLOBAL_DOMAIN}
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: tls-forgejo
        hosts:
        - forgejo.${BCL_GLOBAL_DOMAIN}
      annotations:
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.middlewares: traefik-body-limit-2g@kubernetescrd
    valkey-cluster:
      enabled: true
      cluster:
        nodes: 1
        replicas: 0
    postgresql-ha:
      enabled: false
---
# in cluster ssh access
apiVersion: v1
kind: Service
metadata:
  name: forgejo-in-cluster-ssh
  namespace: forgejo
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
  selector:
    app: forgejo
  type: ClusterIP
