# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  config = lib.mkIf (config.bcl.hardware.device == "virtualbox") {
    bcl.hardware.common = "intel";

    boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" "e1000e" "virtio_pci" "virtio_net" "e1000" ];
    boot.initrd.kernelModules = [ "e1000" ];

    virtualisation.virtualbox.guest.enable = true;
  };

}
