# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: secret-generator
spec:
  interval: 60m
  timeout: 1m
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: secret-generator
  rollback:
    cleanupOnFail: true
  values:
    secretLength: 100
