# yaml-language-server: $schema=../schema/values.schema.json

resources:
  challenges:
    main:
      authorizationURL: https://acme-v02.api.letsencrypt.org/acme/authz/1234
      dnsName: myapp.example.com
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      key: abc123.xyz789
      solver:
        http01:
          ingress:
            ingressClassName: nginx
      token: abc123
      type: HTTP-01
      url: https://acme-v02.api.letsencrypt.org/acme/chall/1234
