---
# Source: base-test/templates/loader.yaml
apiVersion: acme.cert-manager.io/v1
kind: Order
metadata:
  name: test-release
  namespace: default
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  request: MIICZDCCAUwCAQAwHzEdMBsGA1UEAwwUdGVzdC5leGFtcGxlLmludmFsaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9h22nTcaKHE4Jzd57xVaVBwOYRgqPOhiToXfX1b+SrnKg9T6Y8taDaF48v4a2QVK4AJ4JSLOEmjGmFf6Dq6Qq/GOC2kVoB0pCECo/i5u1HHM1FQOTXghx3jqVPXSdz4EzetjnbPrmYo5aSDjw51AVCB41kdsBqT1u4E4NQLTk+V2gD6NiM1+p/sjw4nBeW/Ig5oEZQdo10TgYpHg84dfI92Dmp08QyGQpam7PdodDnMOowvNdZ9kd1klm4GGdw7NxSRiyYePf5ZtG+PV4+RPiYtW+zZpoxJwUApVGsw7yUJVWn4gy19DMW/o3tNliuxLiaBhrTyJJ69F6RzF0lnd1AgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAQEAlHhG6qhunFxNrEedEVQyPPFSVJRy5n21FIAW+DTrhtJoh3S7iJzggQvk2ssf1gYWiYa/fsupBhqFITMZ5U3YOkh0XR8BH30v4rkSnSI8j+gBoyOa5FDsuGJc+YTiEQemJNtjvLMwD197XebDNfBm/oe2dfUoy4zboMlqWW4vWVnZDmT3JybuMAhnIkaNlyotcOC5+47KWEJuwHAmIf8ADHINUZ87c4E/ug4AAkX/VVRw4R+/IGpmtabekoodEr74UdLwAvJwwgCqbO8qASSPd/QCCcXtZE+lWPV9BnbZpqRAdRn59llrL7PndMey04k2ZnnYDC/VfjNXHhqFdGeBVw==
