---
# Source: base-test/templates/loader.yaml
apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  name: test-release
  namespace: default
spec:
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pEQ0NBVXdDQVFBd0h6RWRNQnNHQTFVRUF3d1VkR1Z6ZEM1bGVHRnRjR3hsTG1sdWRtRnNhV1F3Z2dFaQpNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURXRUFzcVlOZXU2ekU5NlZhajZoQU42bGRvCk1nUjIxNmUwVTNKZlFDZ1U4SjR3ei82Mk4vN2V2YnFHUDI0T1dtb2M2Nks3ZjIrVjkwZGxXT1RTbkFiNm5OeEkKREsrYVYxaFpvdE4zZWR2Qm5vMjY1Q2tUbDE2UEp5SHdUWGdSc3paRGFJRnA4R1NFR1AxanYvYWhmZnNKUnI3LwpWcWhjL1ZIUnN4WFZxcEozOXFEQnFHN1JFRFZjTXk0U3c3bmMrY3ViOWdsdkFURUh1R3ArckN3QllUSS80MXFrCk1NOHBuVVNBRjdMS0VhZHgrNzJTWWJuRlg1OC9nUm9iMU0zSEErRndUWkRIdHVvRzJQS0EyY3pTbmNVT0tWdUEKL3VOWThBYWUvMUdMaEUybGlNVkRBVXlvaW1wMkRGdEpqSFM5ZlJaaTVpQml0dnF3YzZDNjZIZUZ6K2h2QWdNQgpBQUdnQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWdyQ3NhM0sxN09iRFlYYm41citCbDFTeStmMjVuZUU1CmN2RGU3cStxUFloaEx1Qi92RDloaFIxWEVIRFVpelNKMDMyNnNNWEZVS0J0TEIySzV4bkdpSkFmdUdFY1llWDkKcmRrZnY5THI4bVVacTduUlpmNjBJZzN6ZW5lTlhKbWhDSjhCMnYwTGdIcThwWVRHTTVXQjRCV3A1SzI5VDlnaApWMW81Sks0OHhGUXhIZHViNEVaSm13MzMyUHBHenhIQ003b1p4NzJHZFpOVGlicVVjd0Y3cS8rVS9JUFhTRXB2CjUvdVphZ0NYSEc4UWIwQ2lDVmMrcXBYQ2RJbk9EZTkzTHNpb3p3cE5IVmhEbVM1UzZDZWlkRHhPZkd0RXphL1AKWVM4cVhFVllJbDA1cHExSTRLOUI2RW94SVJVcGsyblBkNGVWbG1vcFIyd2l1TUZsdmZKTGxnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
