# yaml-language-server: $schema=../schema/values.schema.json

resources:
  certManagerCertificates:
    main:
      secretName: myapp-tls
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      dnsNames:
        - myapp.example.com
