---
# Source: base-test/templates/loader.yaml
apiVersion: v1
data:
  main: cm
kind: ConfigMap
metadata:
  name: test-release-default-enabled
  namespace: default
---
# Source: base-test/templates/loader.yaml
apiVersion: v1
data:
  main: cm
kind: ConfigMap
metadata:
  name: test-release-explicitly-enabled
  namespace: default
