# yaml-language-server: $schema=../schema/values.schema.json

resources:
  imagePolicies:
    main:
      imageRepositoryRef:
        name: main
      policy:
        semver:
          range: ">=1.0.0"
