# yaml-language-server: $schema=../schema/values.schema.json

resources:
  networkPolicies:
    main:
      policyTypes:
        - Ingress
      podSelector:
        matchLabels:
          acme.cert-manager.io/http01-solver: "true"
      ingress:
        - {}
