# yaml-language-server: $schema=../schema/values.schema.json

resources:
  referenceGrants:
    main:
      from:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          namespace: default
      to:
        - group: ""
          kind: Secret
