# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CLI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check-changes.yaml
    with:
      paths: |
        cli/
        .github/workflows/cli.yaml

  build:
    needs: check
    if: needs.check.outputs.changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # whole repo

      - name: Build CLI
        run: cli/gomake build
