# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CLI

on:
  push:
  workflow_dispatch:

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    with:
      paths: |
        cli/
        .github/workflows/cli.yaml

  build:
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # whole repo

      - name: Build CLI
        run: cli/gomake build
