# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker

on:
  push:

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    with:
      paths: |
        docker/
        .github/workflows/docker.yaml

  build:
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download bcl
        run: |
          VERSION="$(grep -E '^\s+version = ' nixos/packages/bcl/default.nix | sed 's/.*"\(.*\)".*/\1/')"
          mkdir -p cli/dist
          curl -fsSL "https://github.com/becloudless/becloudless/releases/download/v${VERSION}/bcl-linux-amd64.tar.gz" \
            | tar -xz -C cli/dist
          chmod +x cli/dist/bcl-linux-amd64/bcl

      - name: Build/Push image
        run: cli/dist/bcl-linux-amd64/bcl ci docker -L trace
