# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Nixos

on:
  push:
  workflow_dispatch:

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    with:
      paths: |
        nixos/
        .github/workflows/nixos.yaml

  build:
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] #, macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # whole repo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: prepare macos
        if: matrix.os == 'macos-latest'
        run: |
          brew install go

      - name: prepare ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install qemu-system qemu-utils -y

      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: test nixos
        run: |
          cd nixos && bash -x ./test.sh
