# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Renovate
on:
  push:

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    with:
      paths: |
        renovate/
        .github/workflows/renovate.yaml

  build:
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: github-app-token
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref_name }}
          token: ${{ steps.github-app-token.outputs.token }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
#          cache: yarn
#          cache-dependency-path: renovate/yarn.lock

      - name: Install
        working-directory: renovate
#        run: yarn --frozen-lockfile --perfer-offline --link-duplicates
        run: npm install yarn && node_modules/yarn/bin/yarn

      - name: Lint Fix
        working-directory: renovate
        run: node_modules/yarn/bin/yarn prettier --write .

      - uses: iarekylew00t/verified-bot-commit@5b4e8852dc472093935b8debcb81459bb79f7986 # v2.3.2
        with:
          ref: ${{ github.ref_name }}
          token: ${{ steps.github-app-token.outputs.token }}
          message: "chore: auto-fix prettier formatting"
          files: |
            renovate/

      - name: Lint
        working-directory: renovate
#        run: yarn lint
        run: node_modules/yarn/bin/yarn lint

      - name: Test
        working-directory: renovate
#        run: yarn test
        run: node_modules/yarn/bin/yarn test
